### PR TITLE
Added TR Lang. For cfx.re

### PR DESCRIPTION
**Pull request by abdulkadiraktas**
Turkish lang. for cfx.re

### CODE REVIEW

**Comment by blattersturm** [comment]
Hi, we don't really do translations using PRs anymore.

**Comment by abdulkadiraktas** [comment]
Why? 
I want to play fivem in Turkish.

**Comment by d0p3t** [comment]
Translations are now done via Weblate. See https://github.com/citizenfx/fivem/pull/485

**Comment by abdulkadiraktas** [comment]
Thanks for reply.

**Comment by abdulkadiraktas** [comment]
All translations are finished btw.

**Pull request closed without merging**
