### PR TITLE
added b2545 map instructional buttons in pausemenu.xml

### PR DESCRIPTION
**Pull request by freedy69**

### CODE REVIEW

**Comment by blattersturm** [comment]
Are there any other missing parts that a diff between 2372 and 2545 would show?

Also, have you tested if this parses correctly on lower versions? Maybe we'll need per-version pausemenu.xml stuff if not. :/

**Comment by freedy69** [comment]
> Are there any other missing parts that a diff between 2372 and 2545 would show?
> 
> Also, have you tested if this parses correctly on lower versions? Maybe we'll need per-version pausemenu.xml stuff if not. :/

it works fine on lower builds, i tested it with 2372. The Contact button has it's own native in 2545 that makes it show, which isn't present in prior builds so there isn't a useless button either. I have no idea what the destination button is for, but it doesn't show either. This is how it looks on 2372: https://i.imgur.com/BQSSV7H.png

**Comment by blattersturm** [comment]
IB_SETDEST doesn't seem to be a 2545 thing as it was even meant to be there in 1604, I'll apply another set of diffs instead of this PR once I track down where this came from.

**Comment by blattersturm** [comment]
Turns out this was added in b573 (a _very_ long time ago!):

```diff
--- "pausemenu.xml"	2017-07-12 05:41:40.875290300 +0200
+++ "pausemenu.xml"	2022-01-11 08:49:34.204460000 +0100
@@ -1212,7 +1212,8 @@
 				<ButtonPrompts>
 				
 					<CMenuButton> <hButtonHash>IB_MS_WARP</hButtonHash>		<ButtonInput>INPUT_FRONTEND_ACCEPT</ButtonInput> <Contexts>*ALL*,MAP_CanWarp, *NONE*,CORONA_BIGMAP_CLOSE, CORONA_BIGMAP_CLOSE_KM</Contexts></CMenuButton>
-					<CMenuButton> <hButtonHash>IB_WAYPOINT</hButtonHash>	<ButtonInput>INPUT_FRONTEND_ACCEPT</ButtonInput> <Contexts>*ALL*,MAP_Waypoint, *NONE*,CORONA_BIGMAP_CLOSE, CORONA_BIGMAP_CLOSE_KM</Contexts></CMenuButton>
+					<CMenuButton> <hButtonHash>IB_WAYPOINT</hButtonHash>	<ButtonInput>INPUT_FRONTEND_ACCEPT</ButtonInput> <Contexts>*ALL*,MAP_Waypoint, *NONE*,CORONA_BIGMAP_CLOSE, CORONA_BIGMAP_CLOSE_KM, MAP_Destination</Contexts></CMenuButton>
+          <CMenuButton> <hButtonHash>IB_SETDEST</hButtonHash>	<ButtonInput>INPUT_FRONTEND_ACCEPT</ButtonInput> <Contexts>*ALL*,MAP_Destination, *NONE*,CORONA_BIGMAP_CLOSE, CORONA_BIGMAP_CLOSE_KM</Contexts></CMenuButton>
 					<CMenuButton> <hButtonHash>IB_ZOOM</hButtonHash>		<ButtonInputGroup>INPUTGROUP_FRONTEND_TRIGGERS</ButtonInputGroup> <Contexts>*ALL*,MAP_CanZoom</Contexts></CMenuButton>
 					<CMenuButton> <hButtonHash>IB_POI</hButtonHash>		<ButtonInput>INPUT_FRONTEND_Y</ButtonInput> <Contexts>*ALL*,MAP_CanDropPOI, *NONE*,CORONA_BIGMAP_CLOSE, CORONA_BIGMAP_CLOSE_KM</Contexts></CMenuButton>
 				<!--	<CMenuButton> <hButtonHash>IB_CRIMINAL</hButtonHash>	<ButtonInput>INPUT_FRONTEND_CANCEL</ButtonInput> <Contexts>*ALL*,MAP_Criminal</Contexts></CMenuButton> -->
```

It appears to be a label that was meant to replace 'Waypoint', as evidenced by the change there as well.

**Pull request closed without merging**
