### PR TITLE
feat(cfx-ui): streamer mode

### PR DESCRIPTION
**Pull request by sharkykh**
This allows streamers to hide sensitive information on the UI, such as server IP addresses.
I based this on the `devMode` setting, hopefully this is good enough :)

### Interface settings:
Setting defaults to **disabled**.

settings

### Linked profiles / accounts:
settings_account

### Profile Avatar:
avatar

### When connecting:
Added new string for `Connecting to server`.

connecting

### On connection failure:
connection-failed

### Server list filter / direct connect:
The input field is now a password field when streamer mode is enabled.

server-filter
server-filter-selected

### CODE REVIEW

**Comment by sharkykh** [comment]
I can't replicate this state I found on Discord (probably because I am only using a local server),
but I assume it is being used after all, so I'm looking into hiding the IP from that as well.

**Comment by Disquse** [comment]
You can also hide these identities I think.
image

**Comment by sharkykh** [comment]
Implemented and updated the screenshots.

**Comment by jaymo1011** [comment]
Would it be possible to add an indication where the text is hidden conveying "hey! you're in streamer mode!" incase a user enables it, forgets, and then wonders *why IP invisible* and *looks like red rectangle* when selected?

Sounds like something that will come up a lot in support questions and giving an immediate indication as to *why* the text is hidden seems like an easy way to prevent that.

**Comment by sharkykh** [comment]
@jaymo1011 
I am actually reworking the server filter this very moment to be a password field.
At first I couldn't get it the way I wanted to, now I figured it out.
It looks much better IMO:

server-filter
server-filter-selected

But regardless, having a "Streamer Mode is enabled" notification seems like a good idea.
I don't really have a design idea in mind, though.

**Comment by jaymo1011** [comment]
> But regardless, having a "Streamer Mode is enabled" ~notification~ warning(?) seems like a good idea.
> **I don't really have a design idea in mind, though.**

With it being a password field, it seems somewhat self explanatory now, a quick "Why is the server address hidden when I type it in?" in the client manual FAQ should *hopefully* clear up most questions.

If not, another section below this with some message conveying *streamer mode enabled therefore input is hidden* should take care of all but the most unobservant of people 😛 
image

**Comment by blattersturm** [comment]
Hi, we'll review and hopefully merge this soon. :)

Perhaps it might be better to pass this to a persistent convar so native code can read it too (and it follows usual setting persistence), though I don't know if `seta` is exposed to UI currently.

**Comment by sharkykh** [comment]
Hi, thank you!

That's a neat idea.
My C++ knowledge is... non-existent, but I will try to do it myself if I can :)

**Comment by blattersturm** [comment]
If `seta` _is_ exposed to a invokeNative call and not just `set`, that's all you'd have to do as everything would be exposed in gameService already - if not, one should follow the current convar setting logic and make one for seta, presumably.

Reference as to seta in the [docs](https://docs.fivem.net/docs/client-manual/console-commands/#seta) except archiving is implemented now and that page is outdated!

**Comment by sharkykh** [comment]
Alright, should be good. I can't build FiveM on my machine, so I tested everything but invoking the native (which is kind of ironic).
I used `seta ui_streamerMode true|false` on the NUI console and it updated in real time, *should* be good.
I'll try the EXE from the AppVeyor build artifacts if that works...

**Comment by JimmisAtha** [comment]
Is it possible to get FiveM on PlayStation???

**Comment by technetium-cfx** [comment]
No, FiveM and RedM are for PC only. Please don't ask such questions on GitHub in the future, we have a wonderful community on the [forums](https://forum.cfx.re/) and [Discord](https://discord.gg/fivem) 🙂

**Pull request merged**
