### PR TITLE
Fix for bigger servers

### PR DESCRIPTION
**Pull request by dutchplayers**
This allowes servers to use more vehicle resources.

Some servers are for high end or friends only.

### CODE REVIEW

**Comment by smallo92** [comment]
You honestly don't need more vehicles then what the game already allows. You are only going to cause more and more issues for your players by doing so. For example the "city bug" or "texture loss" that everyone complains about is directly caused by your monstrous amount of custom vehicles.

**Comment by dutchplayers** [comment]
We want to make our server how we like it. The solution is already there and our users do edit their own client sided files while you can do it for everybody. If your server causes city bug for players, it's your problem. So if we like to allow high end  gaming only its up  to us.

It's just a kind request since it does not cause any crashes or whatever. 

Yes we have a lot resources, 430 now. It's working fine for us and we want to keep expanding since we still hasve 60fps.

**Comment by DamonOnYT** [comment]
This isn't a "fix". This is just you wanting players with less expensive PC's to lag more by changing 1 number.

**Comment by izio38** [comment]
Thanks for the big fix !

... `uhm` `uhm`

**Comment by dutchplayers** [comment]
You are toxic. 

It is a fix for bigger servers.

**Comment by dutchplayers** [comment]
We decide how we make our server you dont decide that. Go play on your own server and leave us alone.

We want to ask de dev to support bigger servers. Thank you.

**Comment by dutchplayers** [comment]
> 
> 
> This isn't a "fix". This is just you wanting players with less expensive PC's to lag more by changing 1 number. Just because you have a good PC doesn't mean everyone else who plays FiveM does.

Dear if your server uses 2000 handling data it wont give lag to players if limit is 8000. :')

**Comment by dutchplayers** [comment]
Or just work harder and buy better pc

**Comment by technetium-cfx** [comment]
> You are toxic.
No one is being toxic. All responses so far have been constructive and descriptive. Calling people out because you are not getting the response you wanted is however, by definition, toxic behavior.

> We decide how we make our server you dont decide that. Go play on your own server and leave us alone.
You are countering your own argument here. You cannot expect us to merge a change that affects _every_ server if only you are having issues. There are good reasons not to increase the limit, and getting a better PC is not one of them. We're open to improvements, but not open to changes that only suit one server.

**Pull request closed without merging**
