### PR TITLE
Updates for build instructions

### PR DESCRIPTION
**Pull request by Jamelele**

### CODE REVIEW

**Comment by blattersturm** [comment]
Can you folks stop trying to touch this document with weird opinions?

**Comment by Jamelele** [comment]
What is opinionated about these changes?

The first fix was to make the example consistent with the instructions above to use Boost 1.71.0 and obviously the symlink instructions are out of date as the 'cache' folder has since been renamed.

**Comment by blattersturm** [comment]
I'm not even sure why the symlink instructions are there in the first place as they're unneeded and explicitly wrong. Most the document is wrong and outdated since the 'fxd' tool exists, in fact, and it's more effort to approve and merge a PR than would be worth it especially for 'tiny' and irrelevant changes.

**Comment by Jamelele** [comment]
Never mind then, I wasn't aware this document was so outdated

**Pull request closed without merging**
