### PR TITLE
Add `GET_WORLD_COORD_FROM_SCREEN_COORD` for RedM

### LINKED ISSUE #1977: [RDR3 REQUEST] Add support for GET_WORLD_COORD_FROM_SCREEN_COORD
Add support for GetWorldCoordFromScreenCoord that is available on FiveM.

https://github.com/citizenfx/fivem/blob/cf859b338ebe362ebeede242b3bb84a8bc4f2d76/code/components/extra-natives-five/src/GraphicsExtraNatives.cpp#L36

I believe should be an easy job

### PR DESCRIPTION
**Pull request by Disquse**
### Goal of this PR

Add `GET_WORLD_COORD_FROM_SCREEN_COORD` native for RedM.

### How is this PR achieving the goal

By adapting related FiveM code for Red Dead Redemption 2 and RedM.

### This PR applies to the following area(s)

RedM

### Successfully tested on

**Game builds:** 1311, 1355, 1436, 1491

**Platforms:** Windows

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### Fixes issues

Fixes #1977 

Demonstration:
[Video](https://github.com/citizenfx/fivem/assets/10367215/0c3e3e1c-2ec0-44c7-88c1-5e5dae1195fd)

### CODE REVIEW

**Comment by Disquse** [comment]
I'm sure they're not correctly named, however I have no idea about proper names. If you want to suggest proper names, feel free :P

**Comment by gottfriedleibniz** [comment]
In V, and referencing `cbuffer rage_matrices` from its shader and empirically playing around with this:

```cpp
struct grcViewport
{
    float m_world[16];
    float m_worldView[16];
    float m_worldViewProj[16];
    float m_inverseView[16]; // m_camMatrix in MumbleVoice; inverse(m_view)
    float m_view[16]; 
    float m_projection[16];
};
```

In RDR's case:

1. `m_viewProjection` is actually `m_projection` (data looks like a perspective projection matrix);
2. `m_projection` looks like `m_view` (lookat) matrix.

Putting this together:

```cpp
struct grcViewport
{
    float m_world[16];
    float m_worldView[16];
    float m_projection[16];
    float m_inverseView[16];
    float m_unknown[16]; 
    float m_view[16];
};
```

Changing the parameter order here makes this function more consistent with DirectX's own [impl](https://github.com/microsoft/DirectXMath/blob/26559da9024f9520ac7a0c633366a46c749d3dea/Extensions/DirectXMathFMA4.h#L251-L252)

**Comment by Disquse** [comment]
Applied your suggestions, @gottfriedleibniz

**Comment by gottfriedleibniz** [comment]
Actually, shit. Apologies for the hoops jumping here.

While I have no issue with just using `m_view`, in our case `Transform` from [DirectX](https://github.com/microsoft/DirectXMath/blob/26559da9024f9520ac7a0c633366a46c749d3dea/Extensions/DirectXMathFMA4.h#L251-L252) would be `m_worldView` (if-ever/whenever the world matrix is something other than an identity matrix). 

Also took a look at the stuttering at extreme locations and something is causing small fluctuations in the projection matrix. It *seems* `0x1426D8837` in 1491.18.2 (`rage::grcViewport::RegeneratePerspective`) called from `0x1426D9E24` (`rage::grcViewport::SetTemporalOffsets`) is suspect. My RDR IDB is incredibly bare however.

**Review by gottfriedleibniz — APPROVED** [review]

**Pull request merged**
