### PR TITLE
Open m_bagName to allow change handlers to use it

### PR DESCRIPTION
**Pull request by lfshr**
As it stands there's no friendly way of creating a change handler for a `StateBag` as there's no way to access the bag name.

### CODE REVIEW

**Comment by lurkmorr228** [comment]
maybe better make the ctor public instead?

**Comment by lurkmorr228** [comment]
maybe better add a method for creating handlers?

**Comment by blattersturm** [comment]
Unsure about this one.

**Comment by lfshr** [comment]
> Unsure about this one.

Any ideas about how this would be resolved then? I haven't done any GTA stuff in a while so I'm vaguely remembering the issue. I couldn't create a change handler for a player's state bag because I couldn't access the player's bag name. You can of course rebuild it manually but that requires the backend knowledge about those keys. Another method to create a change handler could be the solution?

**Pull request closed without merging**
