### PR TITLE
vendor/lua: luaV_gettable modifications

### PR DESCRIPTION
**Pull request by gottfriedleibniz**
See commit messages...

On a similar note, would it be possible to dos2unix, or something along those lines, vendor/lua? There are similar changes I'd like to make in lmathlib, but the line-endings are wildly inconsistent (CRLF vs LF) and the diff's are borderline unreadable.

### CODE REVIEW

**Comment by blattersturm** [comment]
> On a similar note, would it be possible to dos2unix, or something along those lines, vendor/lua? 

Odd - might be these were checked in on a system without `core.autocrlf` enabled.

**Comment by blattersturm** [comment]
Anyway, merged this (since I'm assuming these were tested beforehand :) these assumptions often are wrong so I hope I'm right this time).

**Comment by gottfriedleibniz** [comment]
Also, would there be any objections to expanding the vector math API, similar to slimmath in C#? There are a variety of vecmath operations that would benefit from being implemented in pure C. 

Even the simple point in AABB queries can be optimized significantly.

**Comment by blattersturm** [comment]
Nope, as long as it doesn't get too crazy-specific supporting more math without a native invocation boundary would be fine.

**Pull request merged**
