### PR TITLE
tweak(native-decls): add reference to input mapper/parameter id documentation

### PR DESCRIPTION
**Pull request by spoty123**

### CODE REVIEW

**Comment by jaymo1011** [comment]
Wouldn't "input mapper & parameter id" as a whole *pluralise* into "input mapper & parameter ids"? (not as a possessive)

**Comment by spoty123** [comment]
> Wouldn't "input mapper & parameter id" as a whole _pluralise_ into "input mapper & parameter ids"? (not as a possessive)

What, do you mean? I've included both mappers and IO parameter's ids in the link?

**Comment by lze3** [comment]
> What, do you mean?

[...]?

And he's talking about your grammar.

**Comment by spoty123** [comment]
> And he's talking about your grammar.

Oh, oops.

**Comment by lze3** [comment]
A single id? Think you meant to pluralise that.

**Pull request closed without merging**
