### PR TITLE
Changed russian word "Ошибка" to english "Error".

### PR DESCRIPTION
**Pull request by Eldarien**

### CODE REVIEW

**Comment by Xinerki** [comment]
it's almost you don't like signature features

**Comment by vecchiotom** [comment]
no one touches the memes!!!

**Comment by ElPumpo** [comment]
Grow up and merge this PR

**Comment by Bluethefurry** [comment]
grow down and keep this pr open!

**Comment by blockba5her** [comment]
the memes have to die eventually. it was great while it lasted.

**Comment by IllusiveTea** [comment]
This meme **has** to live on >:( .

**Comment by blockba5her** [comment]
[Let it die](https://www.youtube.com/watch?v=gWL90wryyOw)

**Comment by IllusiveTea** [comment]
**N O**

**Comment by blockba5her** [comment]
Re-open!

**Comment by TomGrobbe** [comment]
🙄 build your own fork if you want it changed, this pr was closed for a reason.

**Comment by vecchiotom** [comment]
This should be locked by @blattersturm

**Comment by ElPumpo** [comment]
Well merge this PR when you've grown a pair.. while you're at it get a better humor

**Comment by vecchiotom** [comment]
When you'll not be so retarded anymore, then i am sure the elements will be able to at least take it into consideration. I don't see what changing that text would add, apart from removing an historical signature, that has been included with fivem since the beginning.

**Comment by Sojobo** [comment]
Just because somethings existed for a long time doesn't make it right. New users probably see that error and have no clue what's happened. Usability vs Nostalgia?

**Comment by blockba5her** [comment]
It's also in the english locale, meaning that it should be *english*. You could always changed it back in this location: `\FiveM.app\citizen\ui\app\assets\locale-en.json`

**Comment by vecchiotom** [comment]
Mmh, weird, i've always seen a detailed description of what happened right after that word, must've been my mind playing tricks on me!

**Comment by vecchiotom** [comment]
Well, yeah, anyway, you can keep trying and writing stupid comments or you could just go back to your lives, up to you, but trust me, you dont wanna see an angry element coming your way.

**Comment by ElPumpo** [comment]
@vecchiotom who the fuck do you think you are. I hope you stand up to similar situations irl

**Comment by mraes** [comment]
@ElPumpo What the fuck did you just fucking say about me, you little shit? Ill have you know I graduated top of my class in the Navy Seals, and Ive been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and Im the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. Youre fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and thats just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little clever comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldnt, you didnt, and now youre paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. Youre fucking dead, kiddo.

**Pull request closed without merging**
