### PR TITLE
increase txd store pool size

### PR DESCRIPTION
**Pull request by EnzoDCdev**
### Goal of this PR

with this update, it will be possible to use clothes made by the most famous creators with many variables and not limit yourself to using old gamebuilds...

for exampe: i have a pack of clothes that works with gamebuild 2802, with the latest gamebuild 3095 I get the error, like many other people, of txd store limit to 105500)

### How is this PR achieving the goal

the pr archive the goal increasing the value...

### This PR applies to the following area(s)

fivem

### Successfully tested on
**Game builds:** .. 

**Platforms:** Windows

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by yannbcf** [comment]
My take is, reduce the amount of assets that you are providing to your users, it is content that they download / stream, simply doubling a pool size is not a solution by itself

**Comment by gottfriedleibniz** [comment]
In an ideal world we continue the work started here: https://github.com/citizenfx/fivem/pull/1419, however, getting that code to a completed and well-tested state would take (an unknown amount of) time.

Vanilla builds of 3095 seem to use a number in the vicinity ~76000 while some servers are apparently adding [33000+](https://github.com/citizenfx/fivem/issues/2094#issuecomment-1631640837). So even with the recent [105500](https://github.com/citizenfx/fivem/pull/2287) bump there is a (known) line being crossed.

Unsure what a reasonable value would be here - the comment above is certainly the safest approach to take.

**Comment by gbalazsfalvi** [comment]
I would really appreciate, if you can accept this PL

**Comment by Pixel-Nomad** [comment]
please increase the pool size currently i'm using 400+ cars in my server with 100+ mlos and lots of lots clothing and litrally hit the 105500 pool mark can we increase it to 155500 and not to 205500 since i think i does include default textures aswell but in general it will gonna hit when gta releases new updates if this pool size counts gta default textures

**Comment by prikolium-cfx** [comment]
> please increase the pool size currently i'm using 400+ cars in my server with 100+ mlos and lots of lots clothing and litrally hit the 105500 pool mark can we increase it to 155500 and not to 205500 since i think i does include default textures aswell but in general it will gonna hit when gta releases new updates if this pool size counts gta default textures

We are designing better and more universal solution for this issue. No ETA but we will try to deliver that as soon as possible.

**Comment by AlphaCarry** [comment]
> please increase the pool size currently i'm using 400+ cars in my server with 100+ mlos and lots of lots clothing and litrally hit the 105500 pool mark can we increase it to 155500 and not to 205500 since i think i does include default textures aswell but in general it will gonna hit when gta releases new updates if this pool size counts gta default textures

did you find the way of increase poolsize?

**Comment by liberty40** [comment]
Any update ?

**Pull request closed without merging**
