### PR TITLE
fix(server/impl): apply all state bag changes on startup

### LINKED ISSUE #1384: GlobalState initialization on server startup
1. Create a resource with a server script that only contains the following:
```lua
GlobalState.TestKey = 0
print("TestKey: " .. GlobalState.TestKey)
```
2. Add the resource to server.cfg
3. Start FXServer
```
[    c-scripting-core] Creating script environments for test
[         script:test] Error loading script server.lua in resource test: @test/server.lua:2: attempt to concatenate a nil value (field 'TestKey')
[         script:test] stack traceback:
[         script:test]  @test/server.lua:2: in main chunk
[    c-scripting-core] Failed to load script server.lua.
[ citizen-server-impl] Started resource test
```

Restarting the resource will 'fix' the problem.

```
cfx> ensure test
[ citizen-server-impl] Stopping resource test
[    c-scripting-core] Creating script environments for test
[         script:test] TestKey: 0
[ citizen-server-impl] Started resource test
```

I started running into this issue after updating to latest artifacts. Test was done on 5461.

### PR DESCRIPTION
**Pull request by thorium-cfx**
* Fixes issue where a set of state bag changes (and potentially other callbacks) on start up were simply discarded.

fixes #1384

### CODE REVIEW

**Comment by fkk-cz** [comment]
I'm still experiencing the same issue https://github.com/citizenfx/fivem/issues/1384 on the latest version (5483). Same repro steps, server script loading after another one failing to initialize GlobalState.

**Comment by thorium-cfx** [comment]
Did you check the value later? (e.g.: with `CreateThread()`). If this (what I fixed) happens then the changes will get applied asynchronously.

**Comment by fkk-cz** [comment]
I never had any issues after switching to initializing everything in CreateThread, but figured this was still an issue since synchronous initialization worked before. Not a big deal, but could cause confusion for people if they are unaware of this.

**Comment by thorium-cfx** [comment]
> I never had any issues after switching to initializing everything in CreateThread, but figured this was still an issue since synchronous initialization worked before. Not a big deal, but could cause confusion for people if they are unaware of this.

Oh no I mean you can now set it at the top of your script now (like you did) and by the time `CreateThread(...)` functions are called it will be set now, so you can read it there.

**Comment by blattersturm** [comment]
... so that still isn't a fix? 🙃

**Comment by fkk-cz** [comment]
> Oh no I mean you can now set it at the top of your script (like you did) and by the time `CreateThread(...)` functions are called it will be set now, so you can read it there.

My original issue involved initializing and trying to print GlobalState outside of a `CreateThread`. I've since switched to initializing everything in new threads, but the original problem still exists.

**Pull request merged**
