### PR TITLE
Added czech language

### PR DESCRIPTION
**Pull request by rex2630**
I added czech language option to locales.ts and i created a file locales-cs.json with newest strings from locales-en.json, they are translated to czech for sure. And its tested, so it should work like a charm :)

### CODE REVIEW

**Comment by rex2630** [comment]
I resolved merge conflicts and added updated strings. If u want to look on my translations projects that i done: https://p4g.cz/42-2/ . If its not enough to proove its gramaticaly correct then i can get some proofreaders that can look thru it :)

**Comment by Mirascz** [comment]
Nice work :)

**Comment by S1X3M** [comment]
Its gramaticaly correct :*

**Comment by PopcornXYeah** [comment]
Awesome work <3 gramaticaly correct.

**Comment by Nafrei** [comment]
Revised and edited.

**Comment by Kekinka** [comment]
Great work. I revised it and it's alright.

**Pull request merged**
