### PR TITLE
Building : Add known issue for C2039

### PR DESCRIPTION
**Pull request by Mathu-lmn**
### Goal of this PR

This PR adds a known issue and how to fix it when trying to build the FiveM client locally

### This PR applies to the following area(s)

Building docs

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
There should never be a workaround for building that involves editing vendor files.

**Comment by DaniGP17** [comment]
I always get that error while trying to compile FiveM in Release instead of debug, so I don't know what's the good solution for this.

**Comment by Mathu-lmn** [comment]
Maybe I should try opening a PR on the range repo then. But the activity looks stale for the last 6 months 😬

**Comment by Mathu-lmn** [comment]
Tho I agree you should never modify a submodule

**Comment by DaniGP17** [comment]
But exactly, what is the reason why this error has started to appear, I don't remember that in the past when compiling it in the release version I got this error

**Comment by Mathu-lmn** [comment]
I'm not 100% sure, but it comes from your compiler that does not includes the string library by default... That's why it works for some people but not everyone.

**Comment by Mathu-lmn** [comment]
> There should never be a workaround for building that involves editing vendor files.

I completely agree, but then what would your advice be ? Cloning the repo on the citizenfx org and making this change (while changing the submodule remote) ?

**Comment by Nobelium-cfx** [comment]
> Cloning the repo on the citizenfx org and making this change (while changing the submodule remote) ?

I think the best way to go is to try making a PR in the vendor repository. See if they accept it. Worth trying at least.

If not - cloning seems to be an option. But I don't think it worth the effort and added complexity to the project.

IIUC we primarily target MSVC (correct me if Im wrong) and it should build fine there.  Can we just specify which compiler to use? And if the user decides to use something else - they are on their own.

**Comment by FabianTerhorst** [comment]
Also its always worth a try to update the submodule, because we are 3,5 years behind.

**Comment by prikolium-cfx** [comment]
Issue is related to Visual Studio toolset major update (in minor version). Our team will completely move to v144 toolset soon and it will be fixed.

**Comment by Mathu-lmn** [comment]
Ok, surprisingly, my PR got merged in a few hours, so I think it's worth looking into updating the submodule to its latest version

**Pull request closed without merging**
