### PR TITLE
unknown -  updated build notes

### PR DESCRIPTION
**Pull request by sfinktah**
has anybody actually tried building this project from scratch lately?

even the one of the CI test builds is broken.

### CODE REVIEW

**Comment by blattersturm** [comment]
The project builds fine as is, your build notes make no sense either.

**Comment by sfinktah** [comment]
"The project builds find as is."

Spoken like someone who hasn't typed

    git submodule update --init --recursive --remote

in a very long time.

**Comment by blattersturm** [comment]
@sfinktah I'm not too sure where the documentation [states to use the --remote flag](https://github.com/citizenfx/fivem/blame/master/docs/building.md#L15), since it does not.

```
--remote
This option is only valid for the update command. Instead of using the superproject’s recorded SHA-1 to update the submodule, use the status of the submodule’s remote-tracking branch. 
```
This seems actually _undesirable_ for building FiveM, and would explain why you had to check out specific submodule versions.

**Comment by sfinktah** [comment]
In retrospect that should have been fairly obvious to me.

Do you perchance have the .pdb files for the pre-compiled v8.dll and v8_platform.dll that come with the binary installation?  

BTW, there are drop-in replacement v8 binaries for 6.8.2 available via nuget, see https://github.com/pmed/v8-nuget  -  though unfortunately they do not have .pdb files either.

**Comment by sfinktah** [comment]
Okay, with a bit of poking and prodding, I have it down to one error.

    code\client\clrcore\Native.cs(9,33,9,37): error CS0246: The type or namespace name 'Hash' could not be found (are you missing a using directive or an assembly reference?)

**Pull request closed without merging**
