### PR TITLE
Client resources controll natives

### PR DESCRIPTION
**Pull request by MrSentex**
FiveM and cheats are a problem for non whitelisted servers so because now cheats hooks natives to trick most anticheats client-side resources adding new natives will stop some cheats for some time because they will hook again those functions too.

I know is not a big fix but idk c++ so is the best thing I can do for helping the community.
These natives will be used on my OpenSource Anti-Cheat project :)

### CODE REVIEW

**Comment by blattersturm** [comment]
... there's already GET_RESOURCE_BY_FIND_INDEX and similar which allow you to do the exact same thing. 

Also, relying on client reporting makes absolutely less than zero sense, since "cheats" that work this way (most don't even add resources so would do nothing in your idea) will likely just hook such functions to prevent scripts like yours from reporting them.

**Comment by MrSentex** [comment]
All cheats need to create a resource (I know people with cheats and I already try to detect them) but because they hook the natives you are not able to know the resource name and index. Event with the resource you mentioned you can't get the resource. I try all the possible ways to get the resource by the existent natives even with a while trying to get resources with a higher index than GetNumResources returns. Only with the name who can be grab from the resmon or from the console start message you can see the resource.

Sry if my english is not the best hehe <3

**Comment by MrSentex** [comment]
Maybe only private cheats are non resource dependent. All cheats I investigated create a resource.

**Comment by blattersturm** [comment]
And what makes you think that these natives, if added, won't be "hooked" by the cheats you claim you have access to?

Also, nope, most cheats work by hijacking a LuaScriptRuntime instance, only one or two (which are detected in recent client versions) add resources to the manager.

**Comment by MrSentex** [comment]
I don't have access to cheats, I'm not okay with those types of software. 
I had to contact some kids for testing xd.

Obviusly they will hook those natives but they will take some days to do it. Well the last cheat I'm working with create a resource an after interact with it to inject code and is not detected.

I'm not trying to be rude or something like that. I'm only trying to help ❤️

**Comment by tringuyenk19** [comment]
Since they block that native, we cannot protect our servers. Everything depends on you. <3
some information about that.
`void Functions::OverwriteNatives()
{
	/*while (true)
	{
		auto getnum = fx::ScriptEngine::GetNativeHandler(HashString("GET_NUM_RESOURCES"));
		if (!getnum)
			MessageBoxA(NULL, "Didn't find GetNumResources()", "", MB_OK);
		else
			MessageBoxA(NULL, "Found GetNumResources()", "", MB_OK);

		std::this_thread::sleep_for(std::chrono::seconds(5));
	}*/

	std::cout << std::hex << "GET_NUM_RESOURCES > " << HashString("GET_NUM_RESOURCES") << std::endl;
	std::cout << std::hex << "GET_RESOURCE_BY_FIND_INDEX > " << HashString("GET_RESOURCE_BY_FIND_INDEX") << std::endl;
	std::cout << std::hex << "LOAD_RESOURCE_FILE > " << HashString("LOAD_RESOURCE_FILE") << std::endl;
	std::cout << std::hex << "NETWORK_IS_IN_SPECTATOR_MODE > " << HashString("NETWORK_IS_IN_SPECTATOR_MODE") << std::endl;

	std::cout << std::hex << "FORMAT_STACK_TRACE > " << HashString("FORMAT_STACK_TRACE") << std::endl;
	std::cout << std::hex << "PROFILER_ENTER_SCOPE > " << HashString("PROFILER_ENTER_SCOPE") << std::endl;
	std::cout << std::hex << "PROFILER_EXIT_SCOPE > " << HashString("PROFILER_EXIT_SCOPE") << std::endl;

	try
	{
		fx::ScriptEngine::RegisterNativeHandler(HashString("GET_NUM_RESOURCES"), [](fx::ScriptContext& context)
		{
			std::vector<fx::Resource*> resources;

			auto manager = fx::ResourceManager::GetCurrent();
			manager->ForAllResources([&](fwRefContainer<fx::Resource> resource)
			{
				bool found = false;
					
				for (std::string& string : executedList)
					if (string.find(resource->GetName()) != std::string::npos)
						found = true;
					
				if(!found)
					resources.push_back(resource.GetRef());
			});

			context.SetResult(resources.size());
		});

		fx::ScriptEngine::RegisterNativeHandler(HashString("GET_RESOURCE_BY_FIND_INDEX"), [](fx::ScriptContext& context)
		{
			int i = context.GetArgument<int>(0);

			std::vector<fx::Resource*> resources = GetAllResources();

			if (i < 0 || i >= resources.size())
			{
				context.SetResult(nullptr);
				return;
			}
			else
			{
				for (std::string& string : executedList)
					if (resources[i]->GetName().find(string) != std::string::npos)
					{
						std::cout << "Blocked resource trying to access " << string << std::endl;
						context.SetResult(nullptr);
						return;
					}
			}

			context.SetResult(resources[i]->GetName());
		});

		fx::ScriptEngine::RegisterNativeHandler(HashString("LOAD_RESOURCE_FILE"), [](fx::ScriptContext& context)
		{
			fx::ResourceManager* resourceManager = fx::ResourceManager::GetCurrent();
			fwRefContainer<fx::Resource> resource = resourceManager->GetResource(context.GetArgument<const char*>(0));

			if (!resource.GetRef())
			{
				std::cout << "Blocked resource trying to access LoadResourceFile from invalid resource" << std::endl;
				context.SetResult(nullptr);
				return;
			}

			for (std::string& string : executedList)
				if (context.GetArgument<const char*>(0) == string.c_str())
				{
					std::cout << "Blocked resource trying to access LoadResourceFile from " << string << std::endl;
					context.SetResult(nullptr);
					return;
				}

			// try opening the file from the resource's home directory
			fwRefContainer<vfs::Stream> stream = vfs::OpenRead(resource->GetPath() + "/" + context.GetArgument<const char*>(1));

			if (!stream.GetRef())
			{
				context.SetResult(nullptr);
				return;
			}

			// static, so it will persist until the next call
			static std::vector<uint8_t> returnedArray;
			returnedArray = stream->ReadToEnd();
			returnedArray.push_back(0); // zero-terminate

			context.SetResult(&returnedArray[0]);
		});

		fx::ScriptEngine::RegisterNativeHandler(0x048746E388762E11, [](fx::ScriptContext& context)
		{
			context.SetResult(false);
		});

		fx::ScriptEngine::RegisterNativeHandler(0x12103B9E0C9F92FB, [](fx::ScriptContext& context)
		{
			context.SetResult(false);
		});

		// TODO:
		// * GET_RESOURCE_METADATA
		// * GET_RESOURCE_STATE
		// * GET_NUM_RESOURCE_METADATA
	}
	catch (...) { MessageBoxA(NULL, "Error while overwriting natives", "redENGINE", MB_OK); }

	try
	{
		fx::ScriptEngine::RegisterNativeHandler(0x1337, [](fx::ScriptContext& context)
		{
			std::string arg = context.GetArgument<const char*>(0);

			std::vector<std::string> menus = Functions::getAuthData()["data"]["products"].get<std::vector<std::string>>();

			for (std::string& menu : menus)
				if (menu.find(arg))
				{
					context.SetResult(true);
					return;
				}

			context.SetResult(false);
		});
	}
	catch(...) { }
}`

**Pull request closed without merging**
