### PR TITLE
feat(v8): add PerformHttpRequest for js

### PR DESCRIPTION
**Pull request by AvarianKnight**
This allows for people to perform HTTP requests without needing an external library.

### CODE REVIEW

**Comment by blattersturm** [comment]
I do not think this is an appropriate solution. Rather, there should be a new ref-callback-based version of the function which should be directly exposed as 'PerformHttpRequest' (as a native), keeping the old method for compatibility with user code that inadvertently relied on it.

**Comment by blattersturm** [comment]
Secondly... require('http')? Not very friendly but it _does_ exist.

**Comment by AvarianKnight** [comment]
> I do not think this is an appropriate solution. Rather, there should be a new ref-callback-based version of the function which should be directly exposed as 'PerformHttpRequest' (as a native), keeping the old method for compatibility with user code that inadvertently relied on it.

Are you talking something along the lines of REGISTER_RAW_NUI_CALLBACK?

**Comment by blattersturm** [comment]
> Are you thinking about something along the lines of REGISTER_RAW_NUI_CALLBACK?

If that uses ref callbacks, yes.

**Comment by l1ru** [comment]
you can use node-fetch for this

**Comment by AvarianKnight** [comment]
> you can use node-fetch for this

> This allows for people to perform HTTP requests **without needing an external library**.

**Comment by blattersturm** [comment]
Abandoned PR, was apparently undesirable as opposed to unifying the native's implementation.

**Pull request closed without merging**
