### PR TITLE
Create الشرق الاوسط الكبير

### PR DESCRIPTION
**Pull request by don1999**

### CODE REVIEW

**Comment by nimoalr** [comment]
What the fuck is that pull request ?

**Comment by IllusiveTea** [comment]
well this doesnt make sense

**Comment by RikoDEV** [comment]
Delete this.

**Comment by 3bodyZZ** [comment]
يا اخي ليش تجيب التخلف على موقع github ??????

**Comment by 3bodyZZ** [comment]
delete or close this PR because it's useless.

**Pull request closed without merging**
