### PR TITLE
added ListEvents for lua and js

### PR DESCRIPTION
**Pull request by tabarra**
Since its not the global list of events, perhaps I should rename it to ListResourceEvents?

### CODE REVIEW

**Comment by blattersturm** [comment]
Hm, what is the use case for this? Why would a resource not know what events they have registered themselves?

**Comment by tabarra** [comment]
Better control and logging.  
I actually used this to find some dynamic event names from a framework.  
Also, some servers are starting to randomize their event names with UUID, having a list might be useful.

**Comment by blattersturm** [comment]
However, since these methods exist in the global scope, wouldn't it make more sense if you need to 'find event names', to simply prefix a script in the correct ScRT, and monkey-patch AddEventHandler, rather than adding a feature to each HLL ScRT that would only be needed in a very small amount of use cases?

**Comment by tabarra** [comment]
Hmm, how would that monkey-patch work?  
you mean changing `global.addEventListener` or editing all the `addEventListener` in the code to call an intermediary logger function?

**Comment by tabarra** [comment]
Not sure how to do that, for now I'm going to use this patch. 
But feel free to close the PR.

**Comment by tabarra** [comment]
BTW @blattersturm, can you give me an example on how to monkey-patch `addEventListener`?  
I'm curious how this is possible, specially on the Lua env.

**Pull request closed without merging**
