### PR TITLE
Scheduler rework to workaround Await issue

### PR DESCRIPTION
**Pull request by ImagicTheCat**
Following this discussion: https://forum.fivem.net/t/citizen-await/92520/16

### CODE REVIEW

**Comment by joelwurtz** [comment]
Since there is less globals, i think this is less error prone, however you should keep same syntax style IMO (4 spaces tabs) otherwise looks good

**Comment by ImagicTheCat** [comment]
It seems to be one tab.

**Comment by ImagicTheCat** [comment]
When this PR will be considered ? This issue prevents the correct usage of basic Lua features (coroutines). I can't release stuff without it.

**Comment by tabarra** [comment]
Any updates?

**Comment by millerp** [comment]
Any updates?

**Comment by rodrigo-apoc** [comment]
Any updates?

**Pull request closed without merging**
