### PR TITLE
feat(extra-natives/five): add IS_FULLSCREEN

### PR DESCRIPTION
**Pull request by Nyakudev**
### Goal of this PR
This PR introduces a new native function that determines whether the client window is in fullscreen mode. This feature can benefit web developers and be useful for some functionalities.

### How is this PR achieving the goal
By adding the native function ```IsFullscreen```, developers can easily check if the client window is in fullscreen mode.

### This PR applies to the following area(s)
- FiveM 
- Natives

### Successfully tested on
- 3258
- 3095
- 2944

**Game builds:**
all

**Platforms:**
Windows

### Checklist
- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [ ] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### Fixes issues
none

### CODE REVIEW

**Comment by Nyakudev** [comment]
Sorry for shitty commits, it's because i have modified the native-decls in github web.

**Comment by AvarianKnight** [comment]
Can you explain what this is needed for? 

> This feature can benefit web developers and be useful for some functionalities.

Isn't very specific.

A feature request like this got shut down before out of fear that people would abuse this for cheat detection

**Comment by Nyakudev** [comment]
> A feature request like this got shut down before out of fear that people would abuse this for cheat detection

What is the problem if it's used to detect cheaters? It's the server problem if it lead to a fake ban.

**Comment by matehun00** [comment]
You can already do this with
```lua
print(GetConvar("profile_vidScreenType", 1))
```

**Comment by Nyakudev** [comment]
> You can already do this with
> 
> ```lua
> print(GetConvar("profile_vidScreenType", 1))
> ```

oh ok good to know but very few people know it adding the native would make it “easier”.

**Comment by AvarianKnight** [comment]
> > A feature request like this got shut down before out of fear that people would abuse this for cheat detection
> 
> What is the problem if it's used to detect cheaters? It's the server problem if it lead to a fake ban.

Because this will lead to servers trying to force players to play in "Fullscreen" or risk being banned because of the *possibility* of the player cheating. 

There is also *no need* for the server to have access to this information, unless you have another reason other than "to detect cheats"

**Comment by prikolium-cfx** [comment]
Thank you for your contribution but our current common goal is to not increase codebase without proper reason for that. I can't find any real use case for that. If you have such use case feel free to provide it, but for now I will close this PR.

**Pull request closed without merging**
