### PR TITLE
index.d.ts: add missing declarations

### PR DESCRIPTION
**Pull request by PichotM**
- resultAsLong
- resultAsObject
- clearTick
- source

### CODE REVIEW

**Comment by TheDumpap** [comment]
Nice, makes things easier :)

**Comment by Xseba360** [comment]
Why is source declared as a string. Isn't it supposed to be a number?

**Comment by PichotM** [comment]
Source is a string

**Comment by Xseba360** [comment]
how come in a `.js` resource the type is `number` ?
```js
addNetEventListener('testEvent', function () {
  // prints 'number' in console
  console.log(typeof source)
  // prints [1], not ['1']
  console.log(JSON.stringify([source]))
});
```

**Comment by PichotM** [comment]
Actually, according to other type definitions, it should be `number|string` but in Lua or in the cpp code 'source' is a string
You can PR this if you want

**Comment by hojgr** [comment]
@PichotM even in Lua its either number or string. `source` in event handlers and commands is `number`, `GetActivePlayers()` has server IDs as string. Leads to insane and hard to debug bugs sometimes...

now I just always `tonumber` any source anywhere. Still wonder why its string sometimes

**Comment by Xseba360** [comment]
This is very confusing.
For example:
https://runtime.fivem.net/doc/natives/?_0x406B4B20
```typescript
// 0x406B4B20 
// GET_PLAYER_NAME
const retval: string = 
	GetPlayerName(
		playerSrc: string
	);
```
The runtime docs specify the `GetPlayerName()` function takes the `source` as a string, but the TypeScript definitions state otherwise (number). Testing this shows passing it as a string fails to return the correct name.
```js
for (const player of GetActivePlayers()) {
  // prints 128
  console.log(player)
  // prints number
  console.log(typeof player)
  // prints Xseba360
  console.log(GetPlayerName(player))
  // prints **Invalid**
  console.log(GetPlayerName(player.toString()))
}
```

**Comment by Zeemahh** [comment]
Correct. On the client, `get_player_name` only takes a number, whereas on the server it takes either a string or number.

On server, iterate from 0-`get_num_player_indices`, calling `get_player_name` passing `get_player_from_index`, returning a string, and you'll see it will return proper name.

**Pull request merged**
