### PR TITLE
Fix sculpture_revival/example mod rpf

### PR DESCRIPTION
**Pull request by CCrumble**
🗺

### CODE REVIEW

**Comment by Jarrrk** [comment]
Can you explain what this fixes?

I want to assume in saying the surrounding area's collision?

**Comment by smallo92** [comment]
It repairs the collisions for the beach sculpture example mod that comes with FiveM

**Comment by CCrumble** [comment]
Fixes poly edge count references

**Comment by blattersturm** [comment]
Merged via 687fe1fd5ebcf8dacec3dd6b3f41c40b569a408d.

**Pull request closed without merging**
