### PR TITLE
Fixed drivingStyle`s type in Tasks.DriveTo method

### PR DESCRIPTION
**Pull request by Harry09**

### CODE REVIEW

**Comment by pongo1231** [comment]
`DrivingStyle` doesn't cover all the possible driving styles, which is why it's `int`.

**Comment by Harry09** [comment]
So, why `DrivingStyle` still don't have all possible styles?

**Comment by pongo1231** [comment]
Because there's a huge list of possible driving styles?

See https://www.vespura.com/drivingstyle/

**Comment by Harry09** [comment]
Okay, I understood.

**Pull request closed without merging**
