### PR TITLE
tweak(data/rdr3): Increase InteriorProxy pool size

### PR DESCRIPTION
**Pull request by Identity-labs**
### Goal of this PR

RDR has 394 vanilla MLOs
This limit let only 56 custom MLOs

Fivem InteriorProxy pool size is currently at 9060

### How is this PR achieving the goal

By increasing pool size value in gameconfig

### This PR applies to the following area(s)

RedM

### Successfully tested on

**Game builds:** all

**Platforms:** Windows

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by outsider31000** [comment]
You can already do this in your manifest I believe but only in canary.
https://github.com/citizenfx/fivem-docs/pull/481

**Comment by Identity-labs** [comment]
No you can't since it's not in the allowed list
https://content.cfx.re/mirrors/client/pool-size-limits/redm.json

**Comment by outsider31000** [comment]
I see, I didn't know about that list.
wondering why is it so small though.

**Comment by prikolium-cfx** [comment]
Thanks for your contribution. We've added InteriorProxy to our redm.json and fivem.json dynamic pool configs.

**Pull request closed without merging**
