### PR TITLE
tweak(font-renderer): force watermark bottom right

### PR DESCRIPTION
**Pull request by alberttheprince**
### Goal of this PR
Watermark currently randomly moves between the top right and bottom right of the player's screen, which is unnecessary. A set position (bottom right was chosen, as it's just a standard/out-of-the-way spot common across the industry) would allow more reliable expectations for the UI.

### How is this PR achieving the goal

Position is hardcoded to bottom right, rather than top and bottom right randomly.

### This PR applies to the following area(s)
FiveM client

### Successfully tested on

**Game builds:** 3258

**Platforms:** Windows, Linux

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### Fixes issues
Quality of life update, frees up the top right of the screen and sets a position for the watermark going forward.

### CODE REVIEW

**Comment by keeganwut** [comment]
Would be nice to have the mods loaded thing be added to this. It's the biggest pest in the FiveM UI.

**Comment by Korioz** [comment]
I'm almost sure it was done like this to prevent people from hiding it easily on stream, videos and such.

**Comment by prikolium-cfx** [comment]
That was done intentionally and we don't plan to change this decision right now.

**Comment by alberttheprince** [comment]
> I'm almost sure it was done like this to prevent people from hiding it easily on stream, videos and such.

Can be hidden now, it used to be 1 corner, 4 corners and then 2 corners, really no reason to have this moving ad its super imposed.

**Pull request closed without merging**
