### PR TITLE
tweak(data/rdr3): Increase FragmentStore, CAmbientMaskVolume, CAmbientMaskVolumeDoor pool size

### PR DESCRIPTION
**Pull request by Identity-labs**
Increase FragmentStore, CAmbientMaskVolume, CAmbientMaskVolumeDoor pool size

### Goal of this PR

This PR allow to create more YFTs, and AMVs

### How is this PR achieving the goal

Editing gameconfig.xml

### This PR applies to the following area(s)

Redm

### Successfully tested on

**Game builds:** 

1311, 1355, 1436, 1491

**Platforms:** 

Windows

### Checklist

- [ x] Code compiles and has been tested successfully.
- [ x] Code explains itself well and/or is documented.
- [ x] My commit message explains what the changes do and what they are for.
- [ x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by Identity-labs** [comment]
maxresdefault

**Comment by ook3D** [comment]
yeah im sure it will help get your changes get merged by closing the PR and posting a meme.

**Comment by Identity-labs** [comment]
We don't need it anymore, we have workaround, since we can't rely on Cfx engagement to make thing going forward :)

**Comment by ook3D** [comment]
lol, "cfx engagement" you realize they have much more important stuff to take care of right?

**Pull request closed without merging**
