### PR TITLE
feat(extra-natives-five): SET_DEFAULT_*_MULTIPLIER natives

### PR DESCRIPTION
**Pull request by DelphinusBeta**
Allows you to go over a multiplier of 1.0 and is not required to be called on tick

Tested on 1604 and 2189

### CODE REVIEW

**Comment by blattersturm** [comment]
OnKillNetwork checks were missing IIRC according to @Disquse

**Comment by Disquse** [comment]
Yes, those natives would affect other servers if player won't restart the game before joining. Please add code which will reset those values to defaults when player is disconnecting from a server. See `SET_MILLISECONDS_PER_GAME_MINUTE` implementation, `OnShutdownSession` stuff specifically.

**Comment by DelphinusBeta** [comment]
Only just seen your message. Using OnKillNetworkDone resets them on disconnect, would you rather I use OnShutdownSession?

**Comment by Disquse** [comment]
> 
> 
> Only just seen your message. Using OnKillNetworkDone resets them on disconnect, would you rather I use OnShutdownSession?

`OnKillNetworkDone` should be fine.

**Review by Disquse — APPROVED** [review]
Sorry for delay, can confirm this works fine, thanks!

**Comment by Walsheyy** [comment]
Are we going to see this merged anytime soon?

**Comment by blattersturm** [comment]
Not sure, this required some review of _what the hell these values it changes do_.

**Comment by Disquse** [comment]
Hey, what was the reason of closing this PR? It wasn't rejected, we just need a bit more time to verify if your changes won't affect other aspects of the game.

**Comment by DelphinusBeta** [comment]
Hey, with further testing using a high multiplier around multiple players, the CNetObjVehicle pool would get filled and lead to further vehicles not spawning or spawning non-networked (leading to commonly referred "desync"). There would also be the limitation of the gameconfig VehicleUpperLimitMP.

I didn't get around to expanding these values, would you recommend for / against expanding them?

**Comment by blattersturm** [comment]
Yet another reason for figuring out population generation range? Hm.

**Pull request closed without merging**
