### PR TITLE
feat(scripting/v8): add PerformHttpRequest

### PR DESCRIPTION
**Pull request by MRV6**

### CODE REVIEW

**Comment by blattersturm** [comment]
I'm not sure if implementing the weird pre-ref-callback API here makes sufficient sense over, say, reworking the actual call (though from a compatibility perspective - maybe?). Also, the TS definition looks incomplete.

**Comment by MRV6** [comment]
I don't think that the TS definition is incomplete, this seems fine. Can you check please ?

**Comment by lze3** [comment]
> 
> 
> I don't think that the TS definition is incomplete, this seems fine. Can you check please ?

The function supports `(url, cb, method, data, headers, options)` as parameters, yet your TS definition is only expecting 2 at max.

You've also got some `let`s where they should be `const`s.

**Comment by MRV6** [comment]
Fixed.

**Pull request closed without merging**
