### PR TITLE
feat(extra-natives-rdr3): SET_MINIMAP_TYPE for both 1311.20 and 1355.

### PR DESCRIPTION
**Pull request by slashkeyvalue**
Not too comfortable with cpp, hopefully this is fine.

### CODE REVIEW

**Comment by blattersturm** [comment]
Will merge this once `rdr3`-specific native decls will work, probably.

**Comment by slashkeyvalue** [comment]
Sounds good

**Comment by blattersturm** [comment]
Been a while and I think we have this support now, can you squash the PR into a single commit?

**Comment by KadDarem** [comment]
Hi @slashkeyvalue 

Do you know if it's possible to add GET_MINIMAP_TYPE() native to get the current value of the minimap type ?

**Pull request merged**
