### PR TITLE
tweak(native-decls): remove unimplemented decls

### PR DESCRIPTION
**Pull request by kams3**
* Renamed `DoorSystemGetSystemSize.md` to `DoorSystemGetSize.md`: actual fn name is DoorSystemGetSize
* Removed `FlagServerAsPrivate.md`: FLAG_SERVER_AS_PRIVATE is not implemented
* Removed `SetSnakeoilForEntry.md`: SET_SNAKEOIL_FOR_ENTRY is not implemented
* Removed `TempBanPlayer.md`: TEMP_BAN_PLAYER is not implemented

### CODE REVIEW

**Comment by ahcenezdh** [comment]
You could add CREATE_PED, because on the documentation CREATE_PED is marked as a RPC, but the RPC version is not used anymore

**Comment by TheIndra55** [comment]
> Removed SetSnakeoilForEntry.md: SET_SNAKEOIL_FOR_ENTRY is not implemented

SET_SNAKEOIL_FOR_ENTRY is implemented in adhesive.

**Comment by blattersturm** [comment]
> You could add CREATE_PED, because on the documentation CREATE_PED is marked as a RPC, but the RPC version is not used anymore

Codegen still stems from the RPC implementation.

**Comment by FabianTerhorst** [comment]
Thanks for your contribution, but this change is replaced by #2666.

**Pull request closed without merging**
