### PR TITLE
feat(resources/core): Bash 4.3 globbing

### LINKED ISSUE #1406: Bash Glob for resource file matching
This issue proposes current 'glob' to be replaced with Bash Glob's syntax, including extglob and brace expansion.  
For the sake of readability, Bash Glob syntax will be used in this issue to implicitly specify possible file matches in context.

## Use case
**Directory depth**
With current syntax, it is impossible to match `client/*.js` without matching `client/html/*.js`.

**Complexity**
Globs can remain more consistent for all resources, allowing complex project structures with less entry chores.  
<details><summary><code>{*.{C,c}lient.*,client/*.*}</code></summary>

[Playground](https://globster.xyz/?q=%7B*.%7BC%2Cc%7Dlient.*%2Cclient%2F*.*%7D&f=manifest.lua%2CShared.Client.net.dll%2Cclient%2FCommands.js%2Cclient%2FEvents.js%2Cclient%2FMenu.js%2Cclient%2Fhtml%2Fapp.js%2Cclient%2Fhtml%2Findex.html%2Cserver%2FEvents.net.dll%2Cserver%2FSync.net.dll%2Csrc%2Fclient.lua%2Csrc%2FFeed.Client.net.dll%2Csrc%2Fserver.lua)
```diff
  resource
- │   fxmanifest.lua
+ │   Shared.Client.net.dll
  │
  ├───client
+ │   │   Commands.js
+ │   │   Events.js
+ │   │   Menu.js
  │   │
  │   └───html
- │           app.js
- │           index.html
  │
  └───server
-         Events.net.dll
-         Sync.net.dll
```
</details>

<details><summary><code>src/?(*.){C,c}lient.{lua,js,net.dll}</code></summary>

[Playground](https://globster.xyz/?q=src%2F%3F(*.)%7BC%2Cc%7Dlient.%7Blua%2Cjs%2Cnet.dll%7D&f=manifest.lua%2CShared.Client.net.dll%2Cclient%2FCommands.js%2Cclient%2FEvents.js%2Cclient%2FMenu.js%2Cclient%2Fhtml%2Fapp.js%2Cclient%2Fhtml%2Findex.html%2Cserver%2FEvents.net.dll%2Cserver%2FSync.net.dll%2Csrc%2Fclient.lua%2Csrc%2FFeed.Client.net.dll%2Csrc%2Fserver.lua)
```diff
  resource
- │   fxmanifest.lua
  │
  └───src
+         client.lua
+         Feed.Client.net.dll
-         server.js
```
</details>

## Caveat
The behaviour is not interchangeable and migration will be necessary for the majority of uses.

## Migration
All 'glob' stars `*` are equivalent to one `**/**`.
A 'glob' qmark `?` is equivalent to `{?,/}`.

### PR DESCRIPTION
**Pull request by MrGriefs**
Implements and resolves #1406
With tests: https://github.com/MrGriefs/glob-cpp
Note: test repo has different driver code, results *may* vary.

### CODE REVIEW

**Comment by MrGriefs** [comment]
This PR is in a working condition, afaik.
image

**Comment by MrGriefs** [comment]
Would you mind re-opening #1406 so it can be linked?

**Comment by prikolium-cfx** [comment]
Thank you for the PR but we going to close it because looks like it's stale and still draft.

**Comment by MrGriefs** [comment]
> Thank you for the PR but we going to close it because looks like it's stale and still draft.

This PR isn't a draft - we're just waiting for a new manifest version to be ready before it can be merged due to containing breaking changes by removing invalid behaviour seen in the currently implemented glob matcher.

**Pull request closed without merging**
