### PR TITLE
onesync/scope: implement scope native

### PR DESCRIPTION
**Pull request by PichotM**
Tested and working.
I don't know if it is the best way to do it.
So please tell me if I need to use something like `eastl::fixed_map` or fix something else.

### CODE REVIEW

**Comment by blattersturm** [comment]
Concurrency issues, perhaps? 😕

**Comment by GRZ-D3V** [comment]
Tested and works for me too

**Comment by Yum1x** [comment]
This pr would be a good alternative to stop using '-1' when triggering some events.

**Comment by blattersturm** [comment]
cool, but

> This branch has conflicts that must be resolved

**Comment by blattersturm** [comment]
Closing lingering PRs.

**Pull request closed without merging**
