### PR TITLE
Reorganize KVP natives and fix Lua example for the "find" functions

### PR DESCRIPTION
**Pull request by Mathu-lmn**
### Goal of this PR

This PR puts all the KVP related native decls in the kvp folder
It also provides a fix for the Lua example script that wasn't working due to a wrong boolean check and a missing Wait

### How is this PR achieving the goal

By moving all the KVP files in the KVP folder and fixing the Lua example in both StartFindKvp and StartFindExternalKvp

### This PR applies to the following area(s)

Natives

**Game builds:** X

**Platforms:** X

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Review by AvarianKnight — COMMENTED** [review]
These don't need a `Wait`, doing so would just slow down getting the KVPs (especially server side, since it ticks once every 50ms).

**Comment by Mathu-lmn** [comment]
Have you tried it ? I can't right now as I'm away but I can next week if needed !

**Comment by AvarianKnight** [comment]
Yes, the example works fine, you don't need to wait to get the kvp string though.

**Comment by Mathu-lmn** [comment]
I wonder why I added it then. I think the client crashed with no wait but I can't check now

**Comment by AvarianKnight** [comment]
Likely crashed with the `until key` because there would never be a key so it would be an infinite loop

**Comment by Mathu-lmn** [comment]
That's why I changed it to `until not key` 😬

**Comment by Mathu-lmn** [comment]
But wouldn't the client crash in a loop with no wait ?

**Comment by AvarianKnight** [comment]
> But wouldn't the client crash in a loop with no wait ?

The old loop (which was `until key`) *would* crash with a endless loop because it would wait for `key to be valid, which it would never be.

The new loop can't crash because if there isn't a key it will break out of the loop.

**Comment by Mathu-lmn** [comment]
Yes, what I meant is that in regular while loops, if you don't put a Wait(0), the Fivem client freezes and you ultimately crash. I'm wondering if it's the case with the repeat operator too

**Comment by Mathu-lmn** [comment]
I've tested without the Wait and it works fine, thanks for the feedback @AvarianKnight

**Review by FabianTerhorst — APPROVED** [review]
Thanks for your contribution.  👍

**Pull request merged**
