### PR TITLE
Added czech

### PR DESCRIPTION
**Pull request by rex2630**
Sorry, for making another pull request, im so dumb that i dont know how to update already pulled one with  deleted branch. This pull request is  adding language-cs.json to  ext/cfx-ui/src/assets/languages and i added czech language to languages.ts

### CODE REVIEW

**Comment by rex2630** [comment]
And i updated one string i forgot about to translate

**Comment by d0p3t** [comment]
This is exactly one of the reasons why **all** pull requests were closed for languages. If you don't know how to use git, don't even submit a PR

**Comment by rex2630** [comment]
Sorry, now its alright. I just deleted branch before, so i couldnt update it, that was my fault and i apologize for it, it wont happen again.

**Comment by rex2630** [comment]
I made i mistake in locales-cs and that made the language to not work, so i tested it in game and now it looks ok

**Comment by rex2630** [comment]
Can anyone merge this please? Its ready

**Pull request closed without merging**
