### PR TITLE
Revert "feat(onesync): add NETWORK_GET_FIRST_ENTITY_OWNER native"

### LINKED ISSUE #884: NetworkGetFirstEntityOwner causes server crash
Description: NetworkGetFirstEntityOwner causes server crash

Repro:
Assuming we have a command to create a vehicle via CREATE_AUTMOBILE native
```
RegisterCommand('vehtest2', function(source, args, RawCommand)
	local ped = GetPlayerPed(source)
	Citizen.InvokeNative(GetHashKey('CREATE_AUTOMOBILE'), GetHashKey(args[1]), GetEntityCoords(ped), GetEntityHeading(ped))
end)
```
Afterward, if we try to fetch the first entity owner of the created vehicle, the server will crash and it only happens when you create a vehicle by CREATE_AUTMOBILE (CreateVehicle RPC native is totally fine)
```
RegisterCommand('getowner', function(source, args, RawCommand)
	local ped = GetPlayerPed(source)
	local vehicle = GetVehiclePedIsIn(ped, vehicle)
	
	if not DoesEntityExist(vehicle) then return print("Vehicle does not exist") end
	print(vehicle)
	print(NetworkGetFirstEntityOwner(vehicle))
end)
```

Expected behavior:  NetworkGetFirstEntityOwner should retrieve the first owner or at least -1 as server

Server artifact: 4304
Server OS: Linux ubuntu

### PR DESCRIPTION
**Pull request by blattersturm**
Backdoor feature used for abusive 'anticheat' workarounds to bad server design, PR made by @spoty123 without specifying any reasoning/description, violates core principle of functionality additions where we _don't make any programmable functionality that will only or largely benefit abusive individuals including 'anticheat' addon sellers, with no other legitimate use case to outweigh it_.

Fixes #669.
Fixes #884.

This reverts commit 3b3b511367b80494a4e7d5a282974434f950f8e8.

### CODE REVIEW

**Comment by ExcaliburGO** [comment]
If you say that this is so useless, what else could I use then to ban people who try to spawn stuff?

**Comment by blattersturm** [comment]
a) this PR revert already got reverted
b) don't 'ban people who try to spawn stuff'? just don't let them spawn stuff
c) stop harassing us.,

**Comment by technetium-cfx** [comment]
This revert was already reverted by itself.

**Comment by ExcaliburGO** [comment]
a) Yes I know this got reverted, but I just updated my server artifact to the latest recommended version and was wondering for half an hour why is this native not working. I'd say it wasn't wise to just remove a native that existed for a fairly long time.
b) Why not? If I ban someone who definetely just got caugh on spawning something, it's more probable that this person won't be cheating later using some less-detected hacks (for example aimbot). I was in fact using entity lockdown for a long time and it served me nice, but I wanted to make people able to use parachutes, and also allow entities to be spawned clientside so that people with high ping still see them instantly, and when I had the option to ban cheaters, I used it with no doubts.
c) I'm not harassing you :) I just thought you may know a much better way to know the spawner of an entity, or of banning the cheater. Other than that, I think removing such a good functionality just because people make money on anticheats based on it feels kind of nonsense, especially that this change probably broke a lot of scripts on people's servers. If someone used the following code construction
```
AddEventHandler("entityCreating", function(ent)
	local owner = NetworkGetFirstEntityOwner(ent)
	if not AntiCheatIsValidEntity(ent) then
		TriggerEvent("BanCheater", owner)
		CancelEvent()
	end
end)
```
it just let people cheat and spawn stuff (script threw an error and didn't delete the entity). It wouldn't be a problem if it was some development build existing for a few hours, but this issue happens both the current recommended and optional builds for Linux.

**Comment by blattersturm** [comment]
also

- parachutes work fine with entity lockdown.
- 'spawning stuff client side so .. ping' makes no sense, if there's such a bug report it, but you probably weren't using the right creation natives.

**Pull request merged**
