### PR TITLE
tweak(ext/natives): add AddStateBagChangeHandler c# example

### PR DESCRIPTION
**Pull request by horseyhorsey**
### Goal of this PR
C# documentation added snippet

### CODE REVIEW

**Comment by ahcenezdh** [comment]
it's cs not c# in the ```

**Review by FabianTerhorst — CHANGES_REQUESTED** [review]
Thanks for your contribution. The change itself is good. Can you change your commit text to follow our commit standard?

```
tweak(ext/natives): add AddStateBagChangeHandler c# example
```

**Comment by FabianTerhorst** [comment]
@horseyhorsey I mean the commit message itself, not the pull request title. When you don't know how it works use https://docs.github.com/en/desktop/managing-commits/amending-a-commit-in-github-desktop or reopen the pull request with a new branch.

**Comment by FabianTerhorst** [comment]
We will manually edit the commit text on merge.

**Comment by FabianTerhorst** [comment]
Merged https://github.com/citizenfx/fivem/commit/1f062c0476f0f07a6370b6b0cd9fb9cd80a8b066

**Pull request closed without merging**
