### PR TITLE
Added run.cmd back

### PR DESCRIPTION
**Pull request by rex2630**
It doesnt work without it

### CODE REVIEW

**Comment by blattersturm** [comment]
it does though?

**Comment by rex2630** [comment]
I tried latest artifacts 2270 and it says 
image

**Comment by smallo92** [comment]
that's because you need to reference FXServer.exe now, not run.cmd

**Comment by blattersturm** [comment]
what's 'it'

that's not something included in this repo or such

**Comment by rex2630** [comment]
It says after running FXServer.exe Idk man, u didnt even tried to run it. You guys are just muting people on discord when they are trying to help. Good luck

**Comment by d0p3t** [comment]
Couldn't reproduce. Works perfectly fine for me without `run.cmd`

```bat
@echo off
set server="D:\fivemserver\server-canary"
set data="D:\fivemserver\server-data-tests"
cd %data%/
%server%\FXServer.exe +exec server.cfg
exit
```

**Comment by rex2630** [comment]
yeah, what did u did for it  to work? Maybe its included in txAdmin somehow or txData, because it doesnt work for me and others

**Comment by smallo92** [comment]
I opened my start.bat file and I changed `run.cmd` to `fxserver.exe`. Real hard hey

**Pull request closed without merging**
