### PR TITLE
Unblocked ScripthookV.NET

### PR DESCRIPTION
**Pull request by WittgenTT5-Rstein**
Title. It's been more than two years by now since ScripthookV.NET got blocked and i'm tired of it, there is no good reason to block it. Put a big fat disclaimer on it for all I care, just don't block it on purpose.

### CODE REVIEW

**Comment by IllusiveTea** [comment]
If you really want it that much, just rename the asi?????? 🤔

**Comment by nathanctech** [comment]
It was intentionally disabled due to the high volume of crashes it causes. As you can tell even scripthook plugins (like simple trainer, lambda, etc) _also_ causes crashes, just in much less frequency.

You can replicate whatever a  SHVNET does by using C# resources. I really don't see the point on allowing a very unstable hook back. All that will happen is people complaining to FiveM about poorly written plugins.

**Comment by IllusiveTea** [comment]
> You can replicate whatever a SHVNET does by using C# resources. I really don't see the point on allowing a very unstable hook back. All that will happen is people complaining to FiveM about poorly written plugins.

Yeah, definitely the best option. Removes the whole requiring client scripts and also allows you to add extra features and whatnot.

**Comment by WittgenTT5-Rstein** [comment]
> 
> 
> If you really want it that much, just rename the asi?????? thinking
Thats what I was doing until 3 March 2017, the day Scripthook got blocked permanently.

Re crashes: my FiveM was rock solid, even with ~~abusing the Knight Rider mod's Turbo Boost~~ quite a few .NET mods.

**Comment by nathanctech** [comment]
> > If you really want it that much, just rename the asi?????? thinking
> 
> Thats what I was doing until 3 March 2017, the day Scripthook got blocked permanently.
> 
> Re crashes: my FiveM was rock solid, even with ~abusing the Knight Rider mod's Turbo Boost~ quite a few .NET mods.

_Your_ FiveM was stable. This isn't a decision just for your wants.

**Comment by IllusiveTea** [comment]
> Re crashes: my FiveM was rock solid, even with abusing the Knight Rider mod's Turbo Boost quite a few .NET mods.

But you cant expect all scripts to function the same? You cant just be like "oh yeah remove this because i know one script works fine!"

**Comment by WittgenTT5-Rstein** [comment]
> 
> 
> > Re crashes: my FiveM was rock solid, even with abusing the Knight Rider mod's Turbo Boost quite a few .NET mods.
> 
> But you cant expect all scripts to function the same? You cant just be like "oh yeah remove this because i know one script works fine!"

And? What do you suppose I should do, compile asi-five.dll without the check myself? If I could code I would have done it in 2017.

**Comment by IllusiveTea** [comment]
> What do you suppose I should do, compile asi-five.dll without the check myself? If I could code I would have done it in 2017.

Did you literally not read like a couple messages up????

> If you really want it that much, just rename the asi?????? 🤔

**Comment by WittgenTT5-Rstein** [comment]
> 
> 
> > What do you suppose I should do, compile asi-five.dll without the check myself? If I could code I would have done it in 2017.
> 
> Did you literally not read like a couple messages up????
> 
> > If you really want it that much, just rename the asi?????? thinking



>
> 
> Thats what I was doing until 3 March 2017, the day Scripthook got blocked permanently.

**Comment by summeryukata** [comment]
why not instead of whitelisting svhdn, make FiveM's C# runtime work for client scripts as well? it is based on svhdn, but has had [countless improvements](https://github.com/citizenfx/fivem/commits/master/code/client/clrcore) over the years.

shvdn at this point would just make your game lag. the native execution is really slow in shvdn compared to clrcore, and it also handles exceptions horribly.

**Comment by IllusiveTea** [comment]
or instead of trying to make all these ways around using scripts on the server, just convert it to C# or Lua? Its not a fairly difficult feat.

**Comment by WittgenTT5-Rstein** [comment]
> 
> 
> why not instead of whitelisting svhdn, make FiveM's C# runtime work for client scripts as well? it is based on svhdn, but has had [countless improvements](https://github.com/citizenfx/fivem/commits/master/code/client/clrcore) over the years.
> 
> shvdn at this point would just make your game lag. the native execution is really slow in shvdn compared to clrcore, and it also handles exceptions horribly.



> 
> 
> or instead of trying to make all these ways around using scripts on the server, just convert it to C# or Lua? Its not a fairly difficult feat.

Try doing that when you've got zero coding knowledge or no access to 3id's KR mod source code. Literally the only reason I want .NET scripts in FiveM is because of the Knight Rider mod. Yeah, i'm a turbo autist like that, fite against me in my Vulcar Ingot Four Thousand :^)

**Comment by nathanctech** [comment]
> > why not instead of whitelisting svhdn, make FiveM's C# runtime work for client scripts as well? it is based on svhdn, but has had [countless improvements](https://github.com/citizenfx/fivem/commits/master/code/client/clrcore) over the years.
> > shvdn at this point would just make your game lag. the native execution is really slow in shvdn compared to clrcore, and it also handles exceptions horribly.
> 
> > or instead of trying to make all these ways around using scripts on the server, just convert it to C# or Lua? Its not a fairly difficult feat.
> 
> Try doing that when you've got zero coding knowledge or no access to 3id's KR mod source code. Literally the only reason I want .NET scripts in FiveM is because of the Knight Rider mod. Yeah, i'm a turbo autist like that, fite against me in my Vulcar Ingot Four Thousand :^)
> 
> With that being said I don't experience any FPS issues or crashes, even with 10 scripts loaded.

Still going on with the "me, me, me" stuff. I don't think this has any chance of being changed simply because *you* want to use it. It has very real implications for everyone else and will just be a royal headache.

**Comment by WittgenTT5-Rstein** [comment]
> 
> 
> > > why not instead of whitelisting svhdn, make FiveM's C# runtime work for client scripts as well? it is based on svhdn, but has had [countless improvements](https://github.com/citizenfx/fivem/commits/master/code/client/clrcore) over the years.
> > > shvdn at this point would just make your game lag. the native execution is really slow in shvdn compared to clrcore, and it also handles exceptions horribly.
> > 
> > 
> > > or instead of trying to make all these ways around using scripts on the server, just convert it to C# or Lua? Its not a fairly difficult feat.
> > 
> > 
> > Try doing that when you've got zero coding knowledge or no access to 3id's KR mod source code. Literally the only reason I want .NET scripts in FiveM is because of the Knight Rider mod. Yeah, i'm a turbo autist like that, fite against me in my Vulcar Ingot Four Thousand :^)
> > With that being said I don't experience any FPS issues or crashes, even with 10 scripts loaded.
> 
> Still going on with the "me, me, me" stuff. I don't think this has any chance of being changed simply because _you_ want to use it. It has very real implications for everyone else and will just be a royal headache.

Then what do you propose?

**Comment by blattersturm** [comment]
Local scripts are not meant to be supported whatsoever. They're on the shortlist for removal, not on the 'we want to give them more capabilities' list.

**Pull request closed without merging**
