### PR TITLE
Create GetPlayerIdentifiers.md

### PR DESCRIPTION
**Pull request by hassony18**

### CODE REVIEW

**Comment by Zeemahh** [comment]
This function only exists in Lua, afaik.

**Comment by hassony18** [comment]
Indeed. I've just checked the other languages and it doesn't work there. However, I am not sure how I can edit a native for a specific language, as you can see: 
image

There are 4 languages but when I click on "Improve this document" it takes me to a single file where I can only edit C language. 
image


Could you please lead me to the proper way to edit it for LUA for example?

**Comment by blattersturm** [comment]
It's not a native. It doesn't belong in natives.

It's already documented in the Lua-specific reference: https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers/

**Comment by hassony18** [comment]
Alright thanks for the clarification. I will close this PR just after you answer my question above: how do I edit a native for a specific language (like LUA only)

**Comment by d0p3t** [comment]
> Alright thanks for the clarification. I will close this PR just after you answer my question above: how do I edit a native for a specific language (like LUA only)

You can't edit anything specific for a language tab. For examples just use markdown. See https://runtime.fivem.net/doc/natives/?_0x06843DA7060A026B

**Pull request closed without merging**
