### PR TITLE
fix(build): clear stringstream properly

### PR DESCRIPTION
**Pull request by Trsak**

### CODE REVIEW

**Comment by blattersturm** [comment]
uh, both clear the stringstream fine?

https://en.cppreference.com/w/cpp/io/basic_stringstream/operator%3D

and this code doesn't even get hit unless logging is on

also your commit message specifies an entirely wrong component

**Comment by Trsak** [comment]
Well I was getting this error while compiling:
`C:\Trsak\projects\fivem\code\components\citizen-server-impl\src\state\ServerGameState.cpp(1710,1): error C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion) `

That fixes it.

Sorry for wrong commit message tho.

**Comment by Trsak** [comment]
> uh, both clear the stringstream fine?
> 
> https://en.cppreference.com/w/cpp/io/basic_stringstream/operator%3D
> 
> and this code doesn't even get hit unless logging is on
> 
> also your commit message specifies an entirely wrong component

Well I was getting this error while compiling:
`C:\Trsak\projects\fivem\code\components\citizen-server-impl\src\state\ServerGameState.cpp(1710,1): error C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion) `

That fixes it.

Sorry for wrong commit message tho.

**Comment by blattersturm** [comment]
Sounds more like your Visual Studio is outdated, then.

**Comment by Trsak** [comment]
> Sounds more like your Visual Studio is outdated, then.

Okay, will try to update it then. AppVeyor builds get the same error tho.
https://ci.appveyor.com/project/citizenfx/fivem/builds/35977372/job/3261tdq2og0vuial

**Comment by blattersturm** [comment]
> AppVeyor builds get the same error tho.

Correct, as VS is outdated there and rebuilding the image doesn't work for some vague reason.

**Pull request closed without merging**
