### PR TITLE
feat: add weapon components getter natives

### PR DESCRIPTION
**Pull request by PichotM**

### CODE REVIEW

**Comment by blattersturm** [comment]
> _No description provided._

Uh, okay?

**Comment by PichotM** [comment]
A lot of people are modifying their game files to increase the clip size, damage, accuracy, recoil, scope type of the weapon game components. It is not possible to 'override' the base components nor detect it so these natives will be useful to kick the players with modified game files.

**Comment by PichotM** [comment]
🙏

**Comment by MatinDark** [comment]
Can you please send an example use of this native please, I don't get what component hash exactly is

**Pull request merged**
