### PR TITLE
Add Lithuanian language

### PR DESCRIPTION
**Pull request by R0JEA**
Add Lithuanian language translations to FiveM

### CODE REVIEW

**Comment by Xinerki** [comment]
did you use google translate or something? because some translations make no sense

**Comment by RoJea32** [comment]
> did you use google translate or something? because some translations make no sense

which ones? :DD

**Comment by Xinerki** [comment]
"watermark" being translated word for word, ignoring the actual meaning.
"Client script'ai leidžiami" what.
"Tiesioginis ryšys" is also not a very accurate translation

**Comment by RoJea32** [comment]
"vandens ženklas" is not a bad translation, you can call it "logotipas" if you want, it's correct both ways
"client script'ai leidžiami" have a better translation for this? :)
"tiesioginis ryšys" can be corrected to "tiesioginis jungimasis" if you're so picky

**Comment by Quattro20v** [comment]
I think it's a good enough translation. Some words are a bit tricky to translate.

**Pull request closed without merging**
