### PR TITLE
Update Debug.cs | Ability to enable/disable Debug

### PR DESCRIPTION
**Pull request by Kolopsel**
Enables developers to easily enable/disable implemented debug messages.

### CODE REVIEW

**Comment by blattersturm** [comment]
Not sure about this.

What's the intended use case, and why expose it as API surface and not, say, something in a lower-level subsystem?

**Comment by Kolopsel** [comment]
You do have a point, however I think it would be much more pleasent to have something like this already implented in the API. Of course you only need a couple of lines here and there to add something similiar to your script, but like I said before this just makes everything regarding debugging a little bit easier and is especially great for people who want to keep their script tidy.

**Comment by blattersturm** [comment]
Huh?

Also, this wouldn't compile/run properly in the first place either, the formatting is all off, and again I'm not sure why this needs to be an API rather than a more global flag.

**Comment by Kolopsel** [comment]
I do not know why the formatting is suddenly off. Last time I checked, it seemed perfectly fine. Anyway now that I think about it, it would probably make more sense to have something like this as a global flag but how would you go about doing that, if I may ask?

**Comment by blattersturm** [comment]
Would be solved by the issues page/warning system once implemented.

**Comment by manups4e** [comment]
for this i simply used the default DEBUG symbol present when you create a new project to print only when in debug compilation

**Pull request closed without merging**
