### PR TITLE
fix(server): fixed CREATE_PED arguments position

### PR DESCRIPTION
**Pull request by michalpk**
Fixed arguments position for CREATE_PED from 1-5 to 0-4.

### CODE REVIEW

**Comment by blattersturm** [comment]
Fixed? Why would that be a fix? That's breaking compatibility, did you forget that client CREATE_PED has an ignored pedType argument?

**Comment by michalpk** [comment]
Yeah, I completely forgot about pedType. Sorry about that. 😇

**Comment by blattersturm** [comment]
That does remind me that server clones of client natives might not be passed into doc output yet, hm.

**Comment by michalpk** [comment]
Yeah, server natives like CREATE_PED, CREATE_OBJECT_NO_OFFSET etc are not passed into docs.

**Comment by slowzy4** [comment]
bro how can i get unbanned from cfx

**Comment by slowzy4** [comment]
?

**Comment by blattersturm** [comment]
By doing what you just did you got blocked from github.com/citizenfx instead, so not doing that would help.

**Pull request closed without merging**
