### PR TITLE
Fixes: Memory leak in CitizenTaskScheduler.Tick

### PR DESCRIPTION
**Pull request by bladecoding**
* Root tasks were added m_inTickTasks and never cleared.
* The memory leak can be seen by simply adding `Debug.WriteLine( $"[TASK] {m_inTickTasks.Count}" );` to the end of CitizenTaskScheduler.Tick and loading up a C# plugin with an OnTick event.
* This is fixed by setting the root m_inTickTasks to null. The locking is also changed a bit to support m_inTickTasks being null. An alternative fix might be to remove from the lastInTickTasks list when a task is completed.

### CODE REVIEW

**Comment by blattersturm** [comment]
Is this pull request actually setting `m_inTickTasks` to null anywhere? It does not appear to do so. 😕

**Comment by RiC0MD** [comment]
We've been running this patch for about a week now and good results, memory leak has ceased and no issues reported.

**Comment by blattersturm** [comment]
So the patch does work on the _server_, does it however break the client if applied to the client runtime library?

**Comment by RiC0MD** [comment]
We're on the fly patching the client side with the above PR, so all testing has been client side, but its 100% working great client/server right now. @bladecoding / myself are with FamilyRP, where its presently being used.  Before hand users were reporting 4-12GB of mem usage after 30-45+ mins and FPS loss, after we started patching their games normal GTA mem usage / FPS rates.

**Comment by blattersturm** [comment]
Noted! Just making sure due diligence was applied to the PR, will click that lovely green 'rebase and merge' button then. 😄

**Comment by RiC0MD** [comment]
Perfect, thank you!

**Pull request merged**
