### PR TITLE
up AnimStore limit to 31000

### PR DESCRIPTION
**Pull request by Pedro-Lucas14**
### Goal of this PR
Currently using build 2802 to switch to the newer build 3095 I have a lot of problems with animations transmitting too many animations, so it would be good to increase this limit so as not to need to remove content.

### How is this PR achieving the goal

the pr archive the goal increasing the value...

### This PR applies to the following area(s)
FiveM

### Successfully tested on

**Game builds:** .. 

**Platforms:** Windows

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by prikolium-cfx** [comment]
Hi Pedro. Thanks for your impact, but right now we are working on more flexible solution for this issue.

**Comment by Pedro-Lucas14** [comment]
@prikolium-cfx Hi, do you have any dates for when this solution will come out?

**Comment by Pedro-Lucas14** [comment]
Hello, is there any possibility that when a solution will come out with the new DLC that came out it will get worse? @prikolium-cfx

**Comment by Alexscr1pt** [comment]
> Hi Pedro. Thanks for your impact, but right now we are working on more flexible solution for this issue.

any developments? we cant update to the newest game build as it puts us over the animstore pool limit.

**Comment by prikolium-cfx** [comment]
> > Hi Pedro. Thanks for your impact, but right now we are working on more flexible solution for this issue.
> 
> any developments? we cant update to the newest game build as it puts us over the animstore pool limit.

Pool resizing feature already release half year ago.

**Comment by Gogsi** [comment]
I don't think AnimStore is one of the pools that's allowed to be resized https://content.cfx.re/mirrors/client/pool-size-limits/fivem.json

**Comment by prikolium-cfx** [comment]
> AnimStore

Is `AnimStore` full name of target tool? If so - I will add that today.

**Comment by Gogsi** [comment]
I think it is
https://github.com/citizenfx/fivem/blob/1035d9b5ef145feff915708e4c02a3300e3a53c9/data/client/citizen/common/data/gameconfig.xml#L140

**Comment by prikolium-cfx** [comment]
> I think it is
> 
> https://github.com/citizenfx/fivem/blob/1035d9b5ef145feff915708e4c02a3300e3a53c9/data/client/citizen/common/data/gameconfig.xml#L140

fivem.json is updated. AnimStore can be extended by 20480 items. But I recommend to extend to value that you really use.

**Comment by Gogsi** [comment]
@Alexscr1pt for reference, you should be able to increase AnimStore to your desired value now, via the [increase_pool_size command](https://docs.fivem.net/docs/server-manual/server-commands/#increase_pool_size-poolname-increase) in your server.cfg

`increase_pool_size "AnimStore" 10000` - put however much you need here, up to 20480.

**Comment by itsAdminPlus** [comment]
Hey I just tried to up the limit for animstore and its not doing anything. 

increase_pool_size "TxdStore" 20000
increase_pool_size "AnimStore" 21150
increase_pool_size "ScaleformStore" 100

I have this in my cfg & TxdStore & ScaleformStore are working as normal but AnimStore not updating at all.

**Comment by Mathu-lmn** [comment]
That's because you can't increase this pool. For a list of increasable pools, see https://content.cfx.re/mirrors/client/pool-size-limits/fivem.json

**Pull request closed without merging**
