### PR TITLE
add GET_AUDIOCONTEXT_FOR_SERVERID as per GET_AUDIOCONTEXT_FOR_CLIENT

### PR DESCRIPTION
**Pull request by isingrel**
add audio context native using server player id instead of client player id as argument

### CODE REVIEW

**Comment by ntanis-dev** [comment]
Awesome! I was about to do this when I realized the despair us - infinity mode users are in.

**Comment by mickeygeecom** [comment]
How is this native working - what does it, or can it do?

**Comment by ntanis-dev** [comment]
> How is this native working - what does it, or can it do?

Its like `GET_AUDIOCONTEXT_FOR_CLIENT` but instead of `Player` it requires a server ID to be used for infinity (big mode) servers where players are split into "instances" and you cannot query a player outside of the client's player instance.

**Comment by mickeygeecom** [comment]
> > How is this native working - what does it, or can it do?
> 
> Its like `GET_AUDIOCONTEXT_FOR_CLIENT` but instead of `Player` it requires a server ID to be used for infinity (big mode) servers where players are split into "instances" and you cannot query a player outside of the client's player instance.

I understand that, but what does the original  `GET_AUDIOCONTEXT_FOR_CLIENT` do? 🤔 Still lacking the purpose of use.

**Comment by orhanasan** [comment]
It is particularly used for adding sound filters for a voice relay from a client indicated by that server ID to the client code is working. Other than that, you can use some "hidden" natives to create filters, just search for them.

**Pull request merged**
