### PR TITLE
Fix runtime streaming native issue with referenceHash

### PR DESCRIPTION
**Pull request by PichotM**
Fix issue reported here https://forum.cfx.re/t/registerstreamingfilefromurl-not-caching-entries-properly/2697294

### CODE REVIEW

**Comment by blattersturm** [comment]
Is this closed because this implementation didn't work, or?

**Comment by PichotM** [comment]
> Is this closed because this implementation didn't work, or?

I'm not familiar with the streaming system and I've discovered that it does not work if two files are the same (for example +hi models/textures)

**Comment by PichotM** [comment]
Any idea how to fix it?

**Comment by PichotM** [comment]
is there anything blocking this PR?

**Comment by blattersturm** [comment]
Mainly, checking if this logic makes sense - using the _header_ as hash seems incorrect as two different RSC files with the same sizes/type would hash as the same in this case. The old ResourceCacheDevice (v1) I believe used the URL as seed, not the pre-read RSC header.

**Pull request closed without merging**
