### PR TITLE
feat(server): drop getEndpoints method, let playerConnecting NETEV serve endpoints

### PR DESCRIPTION
**Pull request by tayandenga**
After reviewing what @blattersturm pointed in his reply to my previous pull request, more friendly solution today.

* Got no tools to check does it build, unfortunately.

### CODE REVIEW

**Comment by blattersturm** [comment]
This change is not compatible with current backend services.

**Comment by tayandenga** [comment]
> This change is not compatible with current backend services.

Damn, what I am missing?

**Comment by dayidir** [comment]
fivem failed to fetch /info.json to obtain policy metadata , Although the Fivem server is open, we cannot login due to this error code.

**Comment by blattersturm** [comment]
> fivem failed to fetch /info.json to obtain policy metadata , Although the Fivem server is open, we cannot login due to this error code.

Okay, but is that related to this pull request? What are you trying to accomplish here?

**Comment by dayidir** [comment]
Since we do not know the cause of the problem, we are only trying to log into the server at the moment.

**Comment by dayidir** [comment]
What is the main cause of this problem? I'm just curious about this. I could only find this page on Google search.

**Comment by blattersturm** [comment]
Merge conflict and apparent incompatibility.

**Pull request closed without merging**
