### PR TITLE
tweak(data/rdr3): Increase PortalInst pool size

### PR DESCRIPTION
**Pull request by Identity-labs**
Hi,

With modding we are able to go out of actual size.
Tested with few peoples no side effect with this new value.

:)

### CODE REVIEW

**Comment by blattersturm** [comment]
Was `PortalInst` this pool of scene graph nodes that is related to some other static sizes, too, or?

**Comment by Identity-labs** [comment]
We have done many tests, we have custom 37 ytyp, 15 custom MLO, with only 30 ytyp active we don't crash, we can disable an MLO in other side of the map to solve this error, ne need to have all portals in same area to crash.
All values are tested with different people.
I don't know what other information is needed ? crash dump ?

**Comment by Identity-labs** [comment]
Previous crash dump need to be analyzed, it's an unknown pool with size limit of 400, not present in gameconfig.xml
But with all of this pool increased this pool crash is not happening.

PortalInst pool crash happen near last ressource sorted by name (start order ?) if we disable a MLO at 5000 meters we don't crash anymore, so i think this pool is global pool, and not rendered portals in scene
Dummy Object is not a crash but console being flooded by max pool size reach and random vanilla MLO miss lot of entities
CLightEntity pool crash happen in st denis by adding light entities in MLO and light entities in area

Those change have been applied on high number of players of our communities without any side effect.

**Comment by blattersturm** [comment]
> it's an unknown pool with size limit of 400, not present in gameconfig.xml

Right, _that's_ the other portal limit that's not likely to be changeable easily.

**Comment by Identity-labs** [comment]
Ok so enable/disable all MLOs in saint denis dynamically with distance of 60 meter solve portal pool issue, so it's a workaround for now.
But we still have Dummy Object pool issue.
I make another PR only with Dummy Object and MapTypesStore ?

**Review by Disquse — APPROVED** [review]

**Comment by Disquse** [comment]
I believe `PortalInst` pool is adjustable without tons of hacks. At least the pool allocation code looks ok after quick analysis.

**Pull request merged**
