### PR TITLE
feat(httphandler): add serverstarted to dynamic.json

### PR DESCRIPTION
**Pull request by pachxl**

### CODE REVIEW

**Comment by blattersturm** [comment]
> _No description provided._

_No closing comment provided._

**Comment by pachxl** [comment]
true

**Comment by aiden-z-source** [comment]
You have added what this does now to your comment (which most, especially bub could have understood). But what is the use case for this?

**Comment by pachxl** [comment]
> You have added what this does now to your comment (which most, especially bub could have understood). But what is the use case for this?

My personal use case is for a website status for any server and also for a discord bot to show the servers status and also alert users when a server is starting up.

**Comment by mickeygeecom** [comment]
If you can't fetch data from the already existing .json's, the server is assumlingly not started and running. This seems unnecessary.

**Comment by pachxl** [comment]
> If you can't fetch data from the already existing .json's, the server is assumlingly not started and running. This seems unnecessary.

I thought that as well but this is not the case

**Comment by blattersturm** [comment]
... then try finding out what goes wrong with whatever you're doing instead of adding a weird 'status' indicator.

**Pull request closed without merging**
