### PR TITLE
feat(extra-natives): add `CNetObject` to `GET_GAME_POOL`

### PR DESCRIPTION
**Pull request by AvarianKnight**
### Goal of this PR
Give a fast path for calls to `GET_GAME_POOL` that only want to get networked objects (which can be a max of 80 objects), reducing the serialization/de-serialization overhead for this native call.

Getting entities from `GetGamePool("CObject")` can be costly due to the fact that this pool will include map objects too, which can lead to this table being thousands of objects long.

This doesn't include networked variants for `CPed` and `CVehicle` because these are more often times going to be networked, where as `CObject` is more likely to be client local objects

### How is this PR achieving the goal
This adds a new fast path `CNetObject` which should only return objects that are networked

<details>
   <summary>Test Example</summary>
   
```lua
CreateThread(function()
    local networkedObjects = GetGamePool("CNetObject")
    for i = 1, #networkedObjects do
        local obj = networkedObjects[i]
        SetEntityAsMissionEntity(obj, true, false)
        DeleteEntity(obj)
    end
end)

local trackedObjectIds = {}
local logged = {}
CreateThread(function()
    local model = `prop_boombox_01`

    RequestModel(model)
    while not HasModelLoaded(model) do
        Wait(0)
    end

    while true do
        local networkedObjects = GetGamePool("CNetObject")
        print("netobj", #networkedObjects)

        for i = 1, #networkedObjects do
            local obj = networkedObjects[i]
            if trackedObjectIds[obj] then
                trackedObjectIds[obj] = false
                print("got tracked object", obj)
            end
        end

        local obj = GetGamePool("CObject")
        print("obj", #obj)

        local pedPos = GetEntityCoords(PlayerPedId())
        local obj = CreateObject(model, pedPos, true, true, false)
        if obj ~= 0 then
            trackedObjectIds[obj] = true
        end

        Wait(1000)
    end
end)
```
</details>

### This PR applies to the following area(s)

FiveM

### Successfully tested on

**Game builds:** N/A

**Platforms:** Windows

### Checklist
- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by Legacy-TacticalGamingInteractive** [comment]
is it possible for an increase beyond 80?

**Comment by AvarianKnight** [comment]
I have no idea.

I don't think using networked objects is typically a good idea anyways, most of the use cases that networked objects will be used for (such as attaching props to a player) are better off with using state bags anyways, or manual syncing (in cases like weed scripts that usually have a static position and wont move)

**Comment by FlawwsX** [comment]
This is a top notch change!

**Review by FabianTerhorst — APPROVED** [review]
Thanks for the contribution 👍

**Pull request merged**
