### PR TITLE
tweak(client/mumble): reduce environmental loudness and reverb in interiors

### PR DESCRIPTION
**Pull request by nikez**

### CODE REVIEW

**Comment by blattersturm** [comment]
Diff for the audio config file?

**Comment by nikez** [comment]
> Diff for the audio config file?

Unk12 from 40 to 15.
```
--- a/categories.dat22_orig_fivem.rel.xml
+++ b/categories.dat22_nikez.rel.xml
@@ -43,7 +43,7 @@
    <Unk09 value="100" />
    <Unk10 value="100" />
    <Unk11 value="100" />
-   <Unk12 value="40" />
+   <Unk12 value="15" />
    <Unk13 value="65" />
    <Unk14 value="50" />
    <Unk15 value="0" />

```

**Comment by blattersturm** [comment]
nice

**Comment by nikez** [comment]
> nice

Could possibly even lower it further, but it sounds good-ish as this, I think. But.. Preferences, I suppose.

**Comment by nikez** [comment]
Also for documentations sake; Unk08 seems to be the volume

**Comment by blattersturm** [comment]
Unk12 -> (int16)rage::Category + 34 -> (float)rage::audCategory + 20 -> multiplied with code setting at + 72 -> g_ResolvedCategorySettings[idx] + 20

Reverb-related, definitely, but not sure if it's source, distance or interior (if present in V) reverb damping value, since code changed too much.

**Comment by blattersturm** [comment]
Other values used in the same function as Unk12 (reverb calculation from audEnvironment):

- Unk15
- Unk13
- Unk10

**Pull request merged**
