### PR TITLE
fix(ui-build): stop focus jumping between iframes on tab presses

### PR DESCRIPTION
**Pull request by dwjft**
https://forum.cfx.re/t/nui-iframe-management-tabbing-between-frames/1491744/12

### CODE REVIEW

**Comment by blattersturm** [comment]
Very tiny nitpick, but most the file uses semicolons and some of your diff doesn't. Can you fix this and squash+force-push such?

**Comment by JulienGelmar** [comment]
This change unfortunately breaks iFrames that are opened inside a NUI iframe. Example code:
```<html>
<head>
<title>reproduction steps</title>
</head>
<body>
<iframe src="http://html.net/tutorials/php/lesson11.php"></iframe>
</body>
</html>
```

If you now attempt to for example focus the search input up top, you will notice any focus events are now being ignored

**Comment by blattersturm** [comment]
> If you now attempt to for example focus the search input up top, you will notice any focus events are now being ignored

Hm - so a nested iframe will blur the patent frame if focused? Would it be possible for you or @dwjft to PR a tweak to this that would e.g. check the hierarchy of a newly focused frame?

Personally I'm only able to look at this in a little while. 😕

**Comment by JulienGelmar** [comment]
To clarify, the search input I am speaking of is inside the secondary iframe. Every input I am clicking inside this html.net website will instantly lose focus.

After some additional testing I can also say that it attempts to focus the input, but instantly loses it.

**Comment by dwjft** [comment]
Looking.

**Comment by dwjft** [comment]
https://github.com/citizenfx/fivem/pull/505

**Pull request merged**
