### PR TITLE
Update GetInvokingResource.md

### PR DESCRIPTION
**Pull request by Greek-Gamer**
Added more info about the native!

### CODE REVIEW

**Comment by jaymo1011** [comment]
Really isn't that informative nor intuitive to a first time reader. This lacks a description and your examples are not well commented, including a weird "cb" pattern.

**Comment by jaymo1011** [comment]
Of course you can try again but you're going to want to understand the *implementation* of the native before you write documentation about it. Read the source for what you're documenting! (If you can't understand the source code however, *you* are probably not the one who should be documenting it.)

**Comment by Greek-Gamer** [comment]
> Of course you can try again but you're going to want to understand the _implementation_ of the native before you write documentation about it. Since this is a CFX native, a native implemented by FiveM itself rather than the game, read the source code for what you're documenting! (If you can't understand the source code however, _you_ are probably not the one who should be documenting it.)

Understood !

**Comment by blattersturm** [comment]
This addition does not add enough value at this time, so we'll be closing this idle PR. See Jaymo's reply above.

**Pull request closed without merging**
