### PR TITLE
fix(ext/cfx-ui/src/assets/languages): Arabic system locale

### PR DESCRIPTION
**Pull request by ahmed608**
### fix(ext/cfx-ui/src/assets/languages): Arabic system locale
- Added a full Arabic translation for the UI strings.
- Ensured the translation respects the original formatting and context.
- Minor adjustments were made to ensure clarity and consistency.

Please review the translation and merge if all looks good. Thanks!

FiveM
Server
UI/Localization
Successfully tested on

Game builds: N/A (applies to UI changes)

Platforms: Windows, Linux

Checklist

 Code compiles and has been tested successfully.
 Code explains itself well and/or is documented.
 My commit message explains what the changes do and what they are for.
 No extra compilation warnings are added by these changes.
Fixes issues

N/A

### CODE REVIEW

**Comment by ahmed608** [comment]
I got tired of changing the name every time.  😇 😅

**Comment by ahmed608** [comment]
and still Some checks were not successful

**Comment by Nobelium-cfx** [comment]
I believe you need to change title of the commit itself. While you are changing title of the PR.

You can amend the commit you've made and force push the change. Something like this should work
```
git commit --amend -m "fix(localization): Arabic system locale"
git push --force
```

**Comment by Nobelium-cfx** [comment]
However, as was mentioned earlier, we currently dont accept localization changes.: https://github.com/citizenfx/fivem/pull/2374#issuecomment-2014057564 . I would have to close this PR for now.

Thank you for your efforts. We really appreciate it regardless.

**Pull request closed without merging**
