### PR TITLE
feat(ext/cfx-ui): missing Czech translations

### PR DESCRIPTION
**Pull request by itIsMaku**
### Goal of this PR
Completed translation of cfx-ui into Czech, formatting correct as in English translation.

### How is this PR achieving the goal
Added missing translations.

### This PR applies to the following area(s)
FiveM UI / RedM UI

### Successfully tested on
**Game builds:** 3258
**Platforms:** Windows

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by matehun00** [comment]
I don't think they do translation PRs

**Comment by itIsMaku** [comment]
> I don't think they do translation PRs

There was already translation for this language, but not updated. I think this should be handy to complete all translations at least. 🤷🏻‍♂️

**Comment by Mathu-lmn** [comment]
This won't get merged unfortunately as they are supposed to implement locales locally 👌

**Comment by prikolium-cfx** [comment]
Thanks for you contribution, but currently we don't accept PRs that provide new locales.

**Pull request closed without merging**
