### PR TITLE
Fix interior extra natives for b2060

### PR DESCRIPTION
**Pull request by Disquse**
TLDR: R* added some weird flag field into CInteriorProxy class struct which is moved interior inst pointer to +8 bytes (flag + 4 bytes of padding), they also removed 8 bytes of padding after inst pointer field, so other interior proxy fields wasn't affected. 

Also contains various small fixes such as:
- Fixed an issue when missing proxy->inst->mloModel caused native execution failures.
- Better structs.
- Fixed typos.

### CODE REVIEW

**Comment by balika011** [comment]
Using templates would be a lot nicer solution

**Comment by blattersturm** [comment]
> Using templates would be a lot nicer solution

How would you see templates used here? I'm mainly thinking of the following, but there's probably a better solution here?

```cpp
struct Blank {};

template<bool Enable, typename T>
using TypeIf = std::conditional_t<Enable, T, Blank>;

// ...
TypeIf<(Build >= 1868), uint32_t> m_field;
```

**Comment by Disquse** [comment]
> 
> 
> > Using templates would be a lot nicer solution
> 
> How would you see templates used here? I'm mainly thinking of the following, but there's probably a better solution.
> 

I was thinking about it, but since there's 3 fields that needs to be changed between 2 versions of the game, I thought that in this case I will be forced to use struct for those 3 fields, so I decided to use the current way. Anyway if you want I can refactor it.

**Comment by blattersturm** [comment]
Merging as is for now.

**Pull request merged**
