### PR TITLE
Corrected Date in MonoScriptRuntime.cpp

### PR DESCRIPTION
**Pull request by NiftyR**

### CODE REVIEW

**Comment by blattersturm** [comment]
the fuck?

**Comment by NiftyR** [comment]
If the message is not incorrect that means the logic for expiring the runtime is incorrect.

**Comment by AvarianKnight** [comment]
Maybe you're misunderstanding?

The values set for the mono runtime are set to expire on [2023-06-30](https://github.com/citizenfx/fivem/blob/1649e2a2afa47d505c078ac472a7a88543c57e12/code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp#L266)

**Comment by jcf54** [comment]
Right, but the prerelease has expired now. We're in GMT timezone, the date local to us is 2023-05-31.

image

**Comment by NiftyR** [comment]
Looking at the code it's likely using || is being the issue since the day could be triggering this if
```cpp
if (time->tm_year > maxYear || time->tm_mon >= maxMonth || time->tm_mday > maxDay)
```

**Comment by AvarianKnight** [comment]
Should probably be
```c++
if (time->tm_year > maxYear || (time->tm_mon >= maxMonth && time->tm_mday > maxDay))
```

**Comment by AvarianKnight** [comment]
> That looks about right, you can see where my confusion came from though surely.

Yes, but it would've been better to report this as an issue instead of making a PR to change the time.

**Pull request closed without merging**
