### PR TITLE
feat(netsync): Serialize CHeliControlDataNode

### PR DESCRIPTION
**Pull request by ahcenezdh**
### Goal of this PR

Serializing the CHeliControlDataNode datanode

### How is this PR achieving the goal
By serializing this data node instead of just parsing it, and after some checks on the 3258 dump, this data node doesn't contain other members.

### This PR applies to the following area(s)
FXServer

### Successfully tested on
Was tested on 2944 & 3095 by checking the return value of the getter `GetLandingGearState()` who call the landingGearState value from CHeliControlDataNode 

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
> I don't know if it's important to add this datanode in ServerSetters with SetupNode (in MakeVehicle) ?

Its not a required node for that. =The only usecase is probably for ServerGameState_Scripting.cpp for getters.

**Comment by ahcenezdh** [comment]
> > I don't know if it's important to add this datanode in ServerSetters with SetupNode (in MakeVehicle) ?
> 
> Its not a required node for that. The only usecase is probably for ServerGameState_Scripting.cpp for getters.

Ok, so it's useless to do it then?

**Comment by FabianTerhorst** [comment]
> > > I don't know if it's important to add this datanode in ServerSetters with SetupNode (in MakeVehicle) ?
> > 
> > 
> > Its not a required node for that. The only usecase is probably for ServerGameState_Scripting.cpp for getters.
> 
> Ok, so it's useless to do it then?

Maybe you can add a few useful getters from this data.

**Comment by ahcenezdh** [comment]
Getters:
 - GetHeliYaw
 - GetHeliPitch
 - GetHeliRoll
 - GetHeliThrottle
 - GetThrusterSideRCSThrottle
 - GetThrusterThrottle
 

Is it good?

**Comment by ahcenezdh** [comment]
Or maybe create a universal native GetVehicleYaw, etcc then get for the vehicle type and return the good value

**Comment by FabianTerhorst** [comment]
> Getters:
> 
> * GetHeliYaw
> * GetHeliPitch
> * GetHeliRoll
> * GetHeliThrottle
> * GetThrusterSideRCSThrottle
> * GetThrusterThrottle
> 
> Is it good?

Should be good enough yes. Im not sure if a generic native for all vehicle types makes much sense for this, because it only seems to be relevant for planes and helis.

**Comment by ahcenezdh** [comment]
> > Getters:
> > 
> > * GetHeliYaw
> > * GetHeliPitch
> > * GetHeliRoll
> > * GetHeliThrottle
> > * GetThrusterSideRCSThrottle
> > * GetThrusterThrottle
> > 
> > Is it good?
> 
> Should be good enough yes. Im not sure if a generic native for all vehicle types makes much sense for this, because it only seems to be relevant for planes and helis.

Yeah those are only for plane/helis.
Ok i'm going to start this when i can

**Comment by ahcenezdh** [comment]
To check if the engine of a heli is running, does GET_IS_VEHICLE_ENGINE_RUNNING is working?

**Comment by ahcenezdh** [comment]
Because i can do a native GET_IS_HELI_ENGINE_RUNNING, or i can directly integrate it into the GET_IS_VEHICLE_ENGINE_RUNNING native

**Comment by FabianTerhorst** [comment]
> To check if the engine of a heli is running, does `GET_IS_VEHICLE_ENGINE_RUNNING` is working? Because i can do a native `GET_IS_HELI_ENGINE_RUNNING`, or i can directly integrate it into the `GET_IS_VEHICLE_ENGINE_RUNNING` native

Afaik the propellers engine is independent of the vehicle engine. But feel free to test that.

**Comment by ahcenezdh** [comment]
> > To check if the engine of a heli is running, does `GET_IS_VEHICLE_ENGINE_RUNNING` is working? Because i can do a native `GET_IS_HELI_ENGINE_RUNNING`, or i can directly integrate it into the `GET_IS_VEHICLE_ENGINE_RUNNING` native
> 
> Afaik the propellers engine is independent of the vehicle engine. But feel free to test that.

I finally created a native `GET_IS_HELI_ENGINE_RUNNING`

Should be good now

**Comment by ahcenezdh** [comment]
I'm going to recreate a cleaner PR

**Pull request closed without merging**
