### PR TITLE
add: onesync_clearPeds

### PR DESCRIPTION
**Pull request by arthur-rl**
Took onesync_clearArea and changed it for peds

### CODE REVIEW

**Comment by jaymo1011** [comment]
Is this something that **needs** to be handled by a built-in command? 

This seems like more of a job for scripting as [`GET_ALL_PEDS`](https://github.com/citizenfx/fivem/blob/637237e69bd73c154a8106a4f26af106748832d1/code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp#L584) exists on the server now.

**Comment by Korioz** [comment]
I personally think that's completely useless and can be scripted by people's themselves 🤷

**Comment by Local9** [comment]
Can't `ClearAreaOfPeds` already do this? Or is this something else?

https://runtime.fivem.net/doc/natives/?_0xBE31FD6CE464AC59

**Comment by blattersturm** [comment]
Not entirely sure what this tries to accomplish - this can be trivially handled by script, hopefully.

**Pull request closed without merging**
