### PR TITLE
tweak(ext/cfx-ui): Hide rateLimiter_* ConVar's

### PR DESCRIPTION
**Pull request by Yum1x**
Inspired by (https://github.com/citizenfx/fivem/pull/2867) this hides all rateLimiter related ConVar's in the server info view

### Goal of this PR

Showing this information to the end-user isn't really helpful, so we hide it.
image
### How is this PR achieving the goal

Adding an exception for "rateLimiter_*" in the server info aggregation function.

### This PR applies to the following area(s)

cfx-ui

### Successfully tested on

**Game builds:** Not applicable

**Platforms:** Windows (Client)

### Checklist

- [X] Code compiles and has been tested successfully.
- [X] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [X] No extra compilation warnings are added by these changes.

### Fixes issues

.

### CODE REVIEW

**Comment by AvarianKnight** [comment]
This shouldn't be shown unless you're specifically setting it via `sets`

**Comment by Yum1x** [comment]
could u help testing on ur own end? 
It was using `sets`w
image

**Comment by AvarianKnight** [comment]
Use `set` instead of `sets` if you don't want it to be included in the vars list.

**Comment by Yum1x** [comment]
misreading the previous comment, closing due to unnecessary and wrong conception.

**Pull request closed without merging**
