### PR TITLE
Added missing Halloween Weather in Array

### PR DESCRIPTION
**Pull request by manups4e**

### CODE REVIEW

**Comment by blattersturm** [comment]
what the hell happened to this commit and why does it change the **entire file**

**Comment by manups4e** [comment]
honestly i don't know i just changed 1 line

**Comment by summeryukata** [comment]
have you by chance used the web editor?

**Comment by manups4e** [comment]
damn yeah i did.. you want me to do it with an external editor and push it to a new forked repo?

**Pull request closed without merging**
