### PR TITLE
WIP Async JS Refs

### PR DESCRIPTION
**Pull request by DiscworldZA**
This adds the beginning of async/await functionality to exports.

Creating async functions as exports and objects with async functions should now be possible.

### CODE REVIEW

**Review by tristenbarkley — APPROVED** [review]

**Comment by Cmoen11** [comment]
What's the hold on this? Maybe someone could be of assistance?

**Comment by blattersturm** [comment]
It being marked as WIP means the author doesn't consider it finalized.

**Comment by Cmoen11** [comment]
Sure @blattersturm But, I'm asking because if there's a pointer of what's missing. Maybe someone could finalize this..

**Comment by blattersturm** [comment]
Why not ask the author? I wouldn't know.

**Comment by Cmoen11** [comment]
Sorry, the question I firstly posted, wasn't for you. It was indeed, for the author.

**Comment by blattersturm** [comment]
Closing out inactive PRs, can reopen if need be.

**Pull request closed without merging**
